// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_City
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_City_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_City_Rowhouse_Intact: Land_SKY_City_Base
	{
		// 3-storey brick townhouse, party walls both sides (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouse_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Rowhouse_Damaged: Land_SKY_City_Base
	{
		// 3-storey brick townhouse, party walls both sides (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouse_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Rowhouse_Ruined: Land_SKY_City_Base
	{
		// 3-storey brick townhouse, party walls both sides (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouse_ruined.p3d";
	};
	class Land_SKY_City_AptBlock_Intact: Land_SKY_City_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblock_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlock_Damaged: Land_SKY_City_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblock_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlock_Ruined: Land_SKY_City_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblock_ruined.p3d";
	};
	class Land_SKY_City_CornerShop_Intact: Land_SKY_City_Base
	{
		// corner bakery with two flats above, shopfront on two streets (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornershop_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerShop_Damaged: Land_SKY_City_Base
	{
		// corner bakery with two flats above, shopfront on two streets (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornershop_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerShop_Ruined: Land_SKY_City_Base
	{
		// corner bakery with two flats above, shopfront on two streets (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornershop_ruined.p3d";
	};
	class Land_SKY_City_OfficeMid_Intact: Land_SKY_City_Base
	{
		// 6-storey glass office building, open plan with corner offices (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officemid_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeMid_Damaged: Land_SKY_City_Base
	{
		// 6-storey glass office building, open plan with corner offices (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officemid_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeMid_Ruined: Land_SKY_City_Base
	{
		// 6-storey glass office building, open plan with corner offices (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officemid_ruined.p3d";
	};
	class Land_SKY_City_Warehouse_Intact: Land_SKY_City_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehouse_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Warehouse_Damaged: Land_SKY_City_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehouse_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Warehouse_Ruined: Land_SKY_City_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehouse_ruined.p3d";
	};
	class Land_SKY_City_Police_Intact: Land_SKY_City_Base
	{
		// 2-storey police station: lobby counter, offices, 3 barred cells (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_police_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Police_Damaged: Land_SKY_City_Base
	{
		// 2-storey police station: lobby counter, offices, 3 barred cells (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_police_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Police_Ruined: Land_SKY_City_Base
	{
		// 2-storey police station: lobby counter, offices, 3 barred cells (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_police_ruined.p3d";
	};
	class Land_SKY_City_RowhouseRender_Intact: Land_SKY_City_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouserender_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhouseRender_Damaged: Land_SKY_City_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouserender_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhouseRender_Ruined: Land_SKY_City_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhouserender_ruined.p3d";
	};
	class Land_SKY_City_RowhousePanel_Intact: Land_SKY_City_Base
	{
		// 2-storey precast townhouse, party walls (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhousepanel_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhousePanel_Damaged: Land_SKY_City_Base
	{
		// 2-storey precast townhouse, party walls (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhousepanel_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhousePanel_Ruined: Land_SKY_City_Base
	{
		// 2-storey precast townhouse, party walls (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_rowhousepanel_ruined.p3d";
	};
	class Land_SKY_City_AptBlockTall_Intact: Land_SKY_City_Base
	{
		// 8-storey precast apartment block (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblocktall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockTall_Damaged: Land_SKY_City_Base
	{
		// 8-storey precast apartment block (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblocktall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockTall_Ruined: Land_SKY_City_Base
	{
		// 8-storey precast apartment block (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblocktall_ruined.p3d";
	};
	class Land_SKY_City_AptBlockBrick_Intact: Land_SKY_City_Base
	{
		// 4-storey brick apartment block (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblockbrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockBrick_Damaged: Land_SKY_City_Base
	{
		// 4-storey brick apartment block (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblockbrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockBrick_Ruined: Land_SKY_City_Base
	{
		// 4-storey brick apartment block (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_aptblockbrick_ruined.p3d";
	};
	class Land_SKY_City_CornerPharmacy_Intact: Land_SKY_City_Base
	{
		// corner pharmacy with two flats above (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerpharmacy_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerPharmacy_Damaged: Land_SKY_City_Base
	{
		// corner pharmacy with two flats above (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerpharmacy_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerPharmacy_Ruined: Land_SKY_City_Base
	{
		// corner pharmacy with two flats above (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerpharmacy_ruined.p3d";
	};
	class Land_SKY_City_CornerHardware_Intact: Land_SKY_City_Base
	{
		// corner hardware store with two flats above (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerhardware_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerHardware_Damaged: Land_SKY_City_Base
	{
		// corner hardware store with two flats above (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerhardware_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerHardware_Ruined: Land_SKY_City_Base
	{
		// corner hardware store with two flats above (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_cornerhardware_ruined.p3d";
	};
	class Land_SKY_City_OfficeTall_Intact: Land_SKY_City_Base
	{
		// 9-storey glass office building (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officetall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeTall_Damaged: Land_SKY_City_Base
	{
		// 9-storey glass office building (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officetall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeTall_Ruined: Land_SKY_City_Base
	{
		// 9-storey glass office building (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_officetall_ruined.p3d";
	};
	class Land_SKY_City_WarehouseSmall_Intact: Land_SKY_City_Base
	{
		// small steel warehouse, 1 roller door (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehousesmall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseSmall_Damaged: Land_SKY_City_Base
	{
		// small steel warehouse, 1 roller door (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehousesmall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseSmall_Ruined: Land_SKY_City_Base
	{
		// small steel warehouse, 1 roller door (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city\sky_city_warehousesmall_ruined.p3d";
	};
};
