// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Underground
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Underground_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Sewer_Straight: Land_SKY_Underground_Base
	{
		// brick sewer, 12 m: channel, two walkways, pipes, lamps; flooding water
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_sewer_straight.p3d";
		class AnimationSources
		{
			class flood
			{
				source = "user";
				animPeriod = 20;
				initPhase = 0;
			};
		};
	};
	class Land_SKY_Sewer_Access: Land_SKY_Underground_Base
	{
		// sewer straight with a side door (+X wall, y 4.0..5.2) to a Sewer_Stair
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_sewer_access.p3d";
		class AnimationSources
		{
			class flood
			{
				source = "user";
				animPeriod = 20;
				initPhase = 0;
			};
		};
	};
	class Land_SKY_Sewer_End: Land_SKY_Underground_Base
	{
		// sewer straight closed at +Y: brick end wall, outfall grating
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_sewer_end.p3d";
		class AnimationSources
		{
			class flood
			{
				source = "user";
				animPeriod = 20;
				initPhase = 0;
			};
		};
	};
	class Land_SKY_Sewer_Junction: Land_SKY_Underground_Base
	{
		// sewer crossing, plank bridges over the channels; flooding water
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_sewer_junction.p3d";
		class AnimationSources
		{
			class flood
			{
				source = "user";
				animPeriod = 20;
				initPhase = 0;
			};
		};
	};
	class Land_SKY_Sewer_Stair: Land_SKY_Underground_Base
	{
		// stair beside a Sewer_Access (+X, same yaw): street opening at -Y, door in its -X wall
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_sewer_stair.p3d";
	};
	class Land_SKY_Metro_Tunnel: Land_SKY_Underground_Base
	{
		// double-track metro box tunnel, 12 m: ballast, sleepers, rails, ledges, cables
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_metro_tunnel.p3d";
	};
	class Land_SKY_Metro_End: Land_SKY_Underground_Base
	{
		// metro tunnel closed at +Y: end wall, buffer stops
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_metro_end.p3d";
	};
	class Land_SKY_Metro_Station: Land_SKY_Underground_Base
	{
		// metro station: island platform, columns, tiles, benches, kiosk, stair to the street (+Y)
		scope = 1;
		model = "SKY_Skyline\sky_underground\sky_metro_station.p3d";
	};
};
