// GENERATED by assets/gen_configs.py from skyspec.KIT (city buildings, D56) - do not edit.
// Intact buildings light up at night; offices / civic / industrial use the cool office light.

class Land_SKY_City_AptBlockBrick_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_AptBlockTall_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_AptBlock_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Bank_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_BarB_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Bar_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CafeBrick_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Cafe_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_ChurchHanged_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Church_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_CinemaB_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Cinema_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Clinic_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_ClubhouseB_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Clubhouse_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CornerHardware_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CornerPharmacy_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CornerShop_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CourtyardBlockBrick_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_CourtyardBlock_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_DepartmentStore_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_FactoryHall_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_FireStation_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_GarageBlock_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_GasStation_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Hospital_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_HypermarketB_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_HyperLight;
	}

	override protected int SkyLightCount()
	{
		return 4;
	}

	void Land_SKY_City_HypermarketB_Intact()
	{
		SKY_Ambience.Register(this, "SKY_Hum_SoundSet", 25.0);
	}

	void ~Land_SKY_City_HypermarketB_Intact()
	{
		SKY_Ambience.Unregister(this);
	}
}

class Land_SKY_City_Hypermarket_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_HyperLight;
	}

	override protected int SkyLightCount()
	{
		return 4;
	}

	void Land_SKY_City_Hypermarket_Intact()
	{
		SKY_Ambience.Register(this, "SKY_Hum_SoundSet", 30.0);
	}

	void ~Land_SKY_City_Hypermarket_Intact()
	{
		SKY_Ambience.Unregister(this);
	}
}

class Land_SKY_City_Kindergarten_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_KioskCafe_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Kiosk_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_MallB_Intact extends SKY_LitBuilding
{
	void Land_SKY_City_MallB_Intact()
	{
		SKY_Ambience.Register(this, "SKY_Muzak_SoundSet", 30.0, "0 4 0");
	}

	void ~Land_SKY_City_MallB_Intact()
	{
		SKY_Ambience.Unregister(this);
	}
}

class Land_SKY_City_Mall_Intact extends SKY_LitBuilding
{
	void Land_SKY_City_Mall_Intact()
	{
		SKY_Ambience.Register(this, "SKY_Muzak_SoundSet", 35.0, "0 6.5 0");
	}

	void ~Land_SKY_City_Mall_Intact()
	{
		SKY_Ambience.Unregister(this);
	}
}

class Land_SKY_City_OfficeMid_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_OfficeTall_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_ParkingGarage_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Police_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_PostOffice_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_RowhousePanel_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_RowhouseRender_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Rowhouse_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_School_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_ShedBrick_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Shed_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_ShopRowHardware_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_ShopRowMarket_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_ShopRowNews_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_ShopRow_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_SupermarketSmall_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Supermarket_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_TownHall_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_VillaBrick_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_VillaStone_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_Villa_Intact extends SKY_LitBuilding
{}

class Land_SKY_City_WarehouseLarge_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_WarehouseSmall_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Warehouse_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_WorkshopBrick_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}

class Land_SKY_City_Workshop_Intact extends SKY_LitBuilding
{
	override protected typename SkyLightType()
	{
		return SKY_OfficeLight;
	}
}
