/*
	Searchable city objects (D61, ROADMAP ideas 13, 16, 19 and 10): bins, dumpsters, garbage trucks,
	the landfill mounds, the mall costume rails / cinema costume trunks and the bar stock; D65: hypermarket
	shelf ends (grocery) and clubhouse lockers (sport); D68: metro ticket kiosks (kiosk) and bus-stop bins (trash);
	D71: clinic medicine cabinets (medical), police gear lockers (police), post office sorting racks (post).

	- Which table: config value `skySearch` of the target class (generated by assets/gen_configs.py
	  from skyspec.SEARCH_TABLE). The client never sends a table, an item name or a position.
	- Where: memory points "search" / "search_1".."search_8" (where the player stands); objects without
	  any (older Dumpster model) use their own position. Read once per type and cached.
	- Server (SKY_SearchService.Search, called from ActionSKY_Search.OnFinishProgressServer):
	  re-checks the table, the distance to a search point, a per-player rate limit and a per-spot
	  cooldown (bounded map), then spawns 0..n items from a fixed server list at the spot.
	APIs: Object.MemoryPointExists / GetMemoryPointPos (3_game/entities/object.c:458-460), ModelToWorld
	(object.c:869), CGame.ConfigGetText (3_game/global/game.c:448), CreateObjectEx (game.c:702),
	ECE_PLACE_ON_SURFACE (3_game/ce/centraleconomy.c), BleedingSourcesManagerServer
	.AttemptAddBleedingSourceBySelection (playerbase.c:1884), PlayerBase.GetItemOnSlot (actionwashhandswell.c).
*/
class SKY_SearchTable
{
	string m_Name;
	float m_HitChance;		//!< chance that the search finds anything
	int m_MaxItems;			//!< 1..m_MaxItems items on a hit
	bool m_CanCut;			//!< bare hands may get cut (broken glass, needles)
	ref array<string> m_Items;

	void SKY_SearchTable(string name, float hitChance, int maxItems, bool canCut, array<string> items)
	{
		m_Name = name;
		m_HitChance = hitChance;
		m_MaxItems = maxItems;
		m_CanCut = canCut;
		m_Items = items;
	}
}

class SKY_SearchService
{
	protected static ref SKY_SearchService s_Instance;
	//! type -> skySearch table name ("" = not searchable). Bounded by the number of config classes.
	protected static ref map<string, string> s_TypeTable = new map<string, string>();
	//! type -> model-space positions of the search memory points (read once per type).
	protected static ref map<string, ref array<vector>> s_TypePoints = new map<string, ref array<vector>>();

	protected ref map<string, ref SKY_SearchTable> m_Tables;
	protected ref map<string, int> m_Spots;			//!< spot key -> time searched (ms)
	protected ref SKY_RateLimiter m_Rate;

	static SKY_SearchService Get()
	{
		if (!s_Instance)
			s_Instance = new SKY_SearchService();
		return s_Instance;
	}

	void SKY_SearchService()
	{
		m_Spots = new map<string, int>();
		m_Rate = new SKY_RateLimiter(SKY_Life.SEARCH_PLAYER_INTERVAL_MS);
		m_Tables = new map<string, ref SKY_SearchTable>();
		// Class names checked against vanilla dayzOffline.chernarusplus db/types.xml (P17: balance).
		array<string> trash = {"Rag", "Paper", "Pen_Black", "BakedBeansCan_Opened", "SardinesCan_Opened", "TunaCan_Opened",
			"SodaCan_Cola", "SodaCan_Pipsi", "GlassBottle", "WaterBottle", "Matchbox", "DuctTape", "Battery9V", "BurlapSack",
			"Rope", "BandageDressing", "Apple", "Chemlight_White", "MetalWire", "Pipe", "WoodenStick", "Rag", "Paper",
			"SodaCan_Cola", "BakedBeansCan_Opened"};
		array<string> landfill = {"Rag", "Paper", "BurlapSack", "Rope", "MetalWire", "Pipe", "WoodenStick", "GlassBottle",
			"WaterBottle", "Pot", "Canteen", "DuctTape", "Battery9V", "Screwdriver", "Pliers", "Hammer", "Hatchet", "Flashlight",
			"Roadflare", "SewingKit", "LeatherSewingKit", "Heatpack", "LongTorch", "ChernarusMap", "Rice", "Matchbox",
			"Chemlight_White", "AntiPestsSpray", "DisinfectantSpray", "Lockpick", "CombatKnife"};
		array<string> costume = {"ManSuit_Beige", "ManSuit_Black", "ManSuit_Blue", "ManSuit_Brown", "ManSuit_DarkGrey",
			"ManSuit_Khaki", "ManSuit_LightGrey", "ManSuit_White", "WomanSuit_Beige", "WomanSuit_Black", "WomanSuit_Blue",
			"WomanSuit_Brown", "WomanSuit_DarkGrey", "WomanSuit_Khaki", "WomanSuit_LightGrey", "WomanSuit_White",
			"MiniDress_BlueChecker", "MiniDress_BlueWithDots", "MiniDress_BrownChecker", "MiniDress_GreenChecker",
			"MiniDress_Pink", "MiniDress_PinkChecker", "MiniDress_RedChecker", "MiniDress_WhiteChecker", "NurseDress_Blue",
			"NurseDress_White", "Skirt_Blue", "Skirt_Red", "Skirt_White", "Skirt_Yellow", "DressShoes_Beige", "DressShoes_Black",
			"DressShoes_Brown", "DressShoes_Sunburst", "DressShoes_White", "MimeMask_Male", "MimeMask_Female"};
		array<string> alcohol = {"SKY_Bottle_Vodka", "SKY_Bottle_Vodka", "SKY_Bottle_Beer", "SKY_Bottle_Beer", "SKY_Bottle_Beer",
			"GlassBottle", "DisinfectantAlcohol"};
		array<string> grocery = {"BakedBeansCan", "PeachesCan", "SpaghettiCan", "TacticalBaconCan", "SardinesCan", "TunaCan", "Rice",
			"Marmalade", "PowderedMilk", "Crackers", "Chips", "SodaCan_Cola", "SodaCan_Pipsi", "SodaCan_Spite", "SodaCan_Kvass",
			"WaterBottle", "Honey", "Zagorky", "ZagorkyChocolate", "ZagorkyPeanuts", "Pajka", "Pate", "BrisketSpread", "BoxCerealCrunchin"};
		array<string> sport = {"TrackSuitJacket_Black", "TrackSuitPants_Black", "AthleticShoes_Black", "AthleticShoes_Blue",
			"AthleticShoes_Grey", "JoggingShoes_Black", "JoggingShoes_Blue", "JoggingShoes_White", "Sneakers_Black", "Sneakers_White",
			"TShirt_Black", "TShirt_Blue", "TShirt_Red", "TShirt_White", "TShirt_RedBlackStripes", "Hoodie_Black", "Hoodie_Grey",
			"SportGlasses_Black", "SportGlasses_Blue", "ShortJeans_Black", "Rag", "WaterBottle"};
		array<string> kiosk = {"Paper", "Paper", "Pen_Black", "Pen_Blue", "ChernarusMap", "Compass", "Zagorky", "ZagorkyChocolate",
			"Crackers", "Chips", "SodaCan_Cola", "SodaCan_Spite", "SodaCan_Kvass", "Matchbox", "PetrolLighter", "Battery9V",
			"Flashlight", "Chemlight_White", "Roadflare", "PersonalRadio"};
		// D71: no firearms or ammunition from searches (the CE keeps control of weapons); classes checked against
		// dayzOffline.chernarusplus db/types.xml like the tables above.
		// common supplies listed several times, the rare ones (IV kit, saline, epinephrine, morphine) once (security L)
		array<string> medical = {"BandageDressing", "BandageDressing", "BandageDressing", "Rag", "Rag", "DisinfectantSpray",
			"DisinfectantAlcohol", "PainkillerTablets", "PainkillerTablets", "CharcoalTablets", "CharcoalTablets",
			"VitaminBottle", "VitaminBottle", "IodineTincture", "Thermometer", "SurgicalGloves_Blue", "SurgicalGloves_Blue",
			"SurgicalMask", "SurgicalMask", "MedicalScrubsShirt_Blue", "TetracyclineAntibiotics", "BloodBagEmpty", "SalineBag",
			"StartKitIV", "Epinephrine", "Morphine"};
		array<string> police = {"PoliceCap", "PoliceJacket", "PolicePants", "PoliceVest", "Handcuffs", "HandcuffKeys",
			"Flashlight", "Battery9V", "Roadflare", "PersonalRadio", "Megaphone", "Chemlight_Red", "BandageDressing"};
		array<string> post = {"Paper", "Paper", "Pen_Black", "Pen_Blue", "Pen_Red", "ChernarusMap", "Compass", "BurlapSack",
			"Rope", "DuctTape", "SewingKit", "Matchbox", "Chemlight_White"};
		m_Tables.Insert("trash", new SKY_SearchTable("trash", 0.6, 1, true, trash));
		m_Tables.Insert("landfill", new SKY_SearchTable("landfill", 0.85, 2, true, landfill));
		m_Tables.Insert("costume", new SKY_SearchTable("costume", 0.9, 1, false, costume));
		m_Tables.Insert("alcohol", new SKY_SearchTable("alcohol", 0.8, 1, false, alcohol));
		m_Tables.Insert("grocery", new SKY_SearchTable("grocery", 0.45, 1, false, grocery));	// D65: hypermarket shelf ends
		m_Tables.Insert("sport", new SKY_SearchTable("sport", 0.7, 1, false, sport));		// D65: clubhouse lockers
		m_Tables.Insert("kiosk", new SKY_SearchTable("kiosk", 0.5, 1, true, kiosk));		// D68: metro kiosks (broken glass)
		m_Tables.Insert("medical", new SKY_SearchTable("medical", 0.35, 1, true, medical));	// D71: clinic cabinets (broken glass)
		m_Tables.Insert("police", new SKY_SearchTable("police", 0.4, 1, false, police));	// D71: police gear lockers
		m_Tables.Insert("post", new SKY_SearchTable("post", 0.5, 1, false, post));			// D71: post office sorting racks
	}

	//! Table name of a target ("" = not searchable). Client and server; cached per type.
	static string TableOf(Object obj)
	{
		string type = obj.GetType();
		string table;
		if (s_TypeTable.Find(type, table))
			return table;
		table = "";
		if (obj.IsBuilding() || obj.IsInherited(House))
			g_Game.ConfigGetText("CfgVehicles " + type + " skySearch", table);
		s_TypeTable.Insert(type, table);
		return table;
	}

	protected static array<vector> PointsOf(Object obj)
	{
		string type = obj.GetType();
		array<vector> pts;
		if (s_TypePoints.Find(type, pts))
			return pts;
		pts = new array<vector>();
		if (obj.MemoryPointExists("search"))
			pts.Insert(obj.GetMemoryPointPos("search"));
		for (int i = 1; i <= SKY_Life.SEARCH_POINTS; i++)
		{
			string name = "search_" + i.ToString();
			if (obj.MemoryPointExists(name))
				pts.Insert(obj.GetMemoryPointPos(name));
		}
		s_TypePoints.Insert(type, pts);
		return pts;
	}

	//! Nearest search spot within reach of `from`: world position and index (-1 = object origin).
	static bool FindSpot(Object obj, vector from, out vector spot, out int idx)
	{
		array<vector> pts = PointsOf(obj);
		idx = -2;
		if (pts.Count() == 0)
		{
			spot = obj.GetPosition();
			if (vector.Distance(spot, from) <= SKY_Life.SEARCH_REACH + 1.0)
				idx = -1;
			return idx == -1;
		}
		float best = SKY_Life.SEARCH_REACH;
		for (int i = 0; i < pts.Count(); i++)
		{
			vector wp = obj.ModelToWorld(pts[i]);
			float d = vector.Distance(wp, from);
			if (d <= best)
			{
				best = d;
				spot = wp;
				idx = i;
			}
		}
		return idx >= 0;
	}

	//! D71: a search spot is where the player stands; nothing solid may lie between the player's eyes and head
	//! height over that spot (a wall, a cell's bars). DayZPhysics.RaycastRV (3_game/global/dayzphysics.c:199),
	//! Geometry LOD (ObjIntersectGeom), the player ignored. Without it the 2 m reach worked through 0.2 m walls.
	static bool InSight(PlayerBase player, vector spot)
	{
		vector from = player.GetPosition() + Vector(0, SKY_Life.SEARCH_EYE, 0);
		vector to = spot + Vector(0, SKY_Life.SEARCH_EYE, 0);
		if (vector.Distance(from, to) < 0.1)
			return true;
		vector hitPos;
		vector hitDir;
		int hitComp;
		return !DayZPhysics.RaycastRV(from, to, hitPos, hitDir, hitComp, null, null, player, false, false, ObjIntersectGeom);
	}

	//! Server: the whole decision. Called from ActionSKY_Search.OnFinishProgressServer.
	void Search(PlayerBase player, Object obj)
	{
		if (!g_Game.IsServer() || !player || !obj || !player.IsAlive())
			return;
		PlayerIdentity identity = player.GetIdentity();
		if (!identity)
			return;
		SKY_SearchTable table;
		if (!m_Tables.Find(TableOf(obj), table))
			return;
		vector spot;
		int idx;
		if (!FindSpot(obj, player.GetPosition(), spot, idx))
			return;
		if (idx >= 0 && !InSight(player, spot))
		{
			player.MessageStatus("Something is in the way.");			// D72: tell the player why (no cooldown used)
			return;													// D71 security M: no searching through a wall
		}
		int now = g_Game.GetTime();
		if (!m_Rate.Allow(identity.GetId(), now))
			return;

		vector op = obj.GetPosition();
		int ox = Math.Round(op[0]);
		int oz = Math.Round(op[2]);
		string key = obj.GetType() + "@" + ox.ToString() + ":" + oz.ToString() + "#" + idx.ToString();
		int last;
		if (m_Spots.Find(key, last) && now - last < SKY_Life.SEARCH_COOLDOWN_MS)
		{
			player.MessageStatus("Someone has already been through this.");
			return;
		}
		if (!m_Spots.Contains(key) && m_Spots.Count() >= SKY_Life.SEARCH_MAX_SPOTS && !Prune(now))
			return;															// fail closed: no loot while full
		m_Spots.Set(key, now);

		bool found = Math.RandomFloat01() < table.m_HitChance;
		if (found)
		{
			int n = Math.RandomIntInclusive(1, table.m_MaxItems);
			// D68: below the terrain (metro kiosk) never trace to a surface - the item could land on the street
			// above; keep the spot height instead (ECE_KEEPHEIGHT / ECE_NOSURFACEALIGN, ce/centraleconomy.c:26-27).
			bool below = spot[1] < g_Game.SurfaceY(spot[0], spot[2]) - 0.5;		// game.c:1162
			int flags = ECE_PLACE_ON_SURFACE;
			float lift = 0.3;
			if (below)
			{
				flags = ECE_CREATEPHYSICS | ECE_KEEPHEIGHT | ECE_NOSURFACEALIGN;
				lift = 0.05;
			}
			for (int k = 0; k < n; k++)
			{
				vector p = spot + Vector(Math.RandomFloatInclusive(-0.4, 0.4), lift, Math.RandomFloatInclusive(-0.4, 0.4));
				g_Game.CreateObjectEx(table.m_Items.GetRandomElement(), p, flags);
			}
			player.MessageStatus("You found something.");
		}
		else
		{
			player.MessageStatus("Nothing useful.");
		}

		if (table.m_CanCut && !player.GetItemOnSlot("Gloves") && Math.RandomFloat01() < SKY_Life.SEARCH_CUT_CHANCE)
		{
			if (player.GetBleedingManagerServer())
				player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
			player.MessageImportant("You cut your hand on broken glass.");
		}
	}

	//! Drop expired spots; false if the map is still full.
	protected bool Prune(int now)
	{
		array<string> stale = new array<string>();
		foreach (string k, int t : m_Spots)
		{
			if (now - t >= SKY_Life.SEARCH_COOLDOWN_MS)
				stale.Insert(k);
		}
		foreach (string s : stale)
			m_Spots.Remove(s);
		return m_Spots.Count() < SKY_Life.SEARCH_MAX_SPOTS;
	}
}
