// GENERATED by assets/gen_configs.py from skyspec.CORE_VARIANTS (tall tower cores, D58) - do not edit.
// The elevator reads skyStops[] from config; a taller core only needs its own class name.

class Land_SKY_TowerA_Core15 extends Land_SKY_TowerA_Core
{
}

class Land_SKY_TowerA_Core23 extends Land_SKY_TowerA_Core
{
}

class Land_SKY_TowerA_Core33 extends Land_SKY_TowerA_Core
{
}
