// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Floors
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Floors_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Floor_Apartments: Land_SKY_Floors_Base
	{
		// typical floor: 4 apartments around a hall ring that wraps the core
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_apartments.p3d";
	};
	class Land_SKY_Floor_Hotel: Land_SKY_Floors_Base
	{
		// typical floor: corridor around the core, 4 guest rooms + 2 suites with 4 connecting corner rooms
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_hotel.p3d";
	};
	class Land_SKY_Floor_Mechanical: Land_SKY_Floors_Base
	{
		// plant floor: opaque louvre facade, 4 plant units
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_mechanical.p3d";
	};
	class Land_SKY_Roof_Garden: Land_SKY_Floors_Base
	{
		// roof terrace: parapet, 4 planters with shrubs, 4 roof-drop points
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_roof_garden.p3d";
	};
	class Land_SKY_Roof_Mechanical: Land_SKY_Floors_Base
	{
		// plant roof: parapet, 4 HVAC units, 4 roof-drop points
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_roof_mechanical.p3d";
	};
	class Land_SKY_Roof_Crown: Land_SKY_Floors_Base
	{
		// HQ crown roof: parapet, setback glass lantern, steel crown fins, 24 m spire with obstruction lights
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_roof_crown.p3d";
	};
	class Land_SKY_Floor_Office_Concrete: Land_SKY_Floors_Base
	{
		// typical office floor: precast concrete panels with ribbon windows
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_office_concrete.p3d";
	};
	class Land_SKY_Floor_Office_Brick: Land_SKY_Floors_Base
	{
		// typical office floor: brick facade with ribbon windows
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_office_brick.p3d";
	};
	class Land_SKY_Floor_HQ: Land_SKY_Floors_Base
	{
		// HQ office floor: dark curtain wall, bronze fins and ribbed spandrels, granite piers (4K atlas)
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_hq.p3d";
	};
	class Land_SKY_Skybridge: Land_SKY_Floors_Base
	{
		// enclosed glazed walkway, 24 m span between two tower roofs, landings with steps over the parapets
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_skybridge.p3d";
	};
};
