// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Floors
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Floors_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Floor_Apartments: Land_SKY_Floors_Base
	{
		// typical floor: 4 apartments around a hall ring that wraps the core
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_apartments.p3d";
	};
	class Land_SKY_Floor_Hotel: Land_SKY_Floors_Base
	{
		// typical floor: corridor ring, 8 guest rooms + 2 suites
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_hotel.p3d";
	};
	class Land_SKY_Floor_Mechanical: Land_SKY_Floors_Base
	{
		// plant floor: opaque louvre facade, 4 plant units
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_floor_mechanical.p3d";
	};
	class Land_SKY_Roof_Garden: Land_SKY_Floors_Base
	{
		// roof terrace: parapet, 4 planters with shrubs, 4 roof-drop points
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_roof_garden.p3d";
	};
	class Land_SKY_Roof_Mechanical: Land_SKY_Floors_Base
	{
		// plant roof: parapet, 4 HVAC units, 4 roof-drop points
		scope = 1;
		model = "SKY_Skyline\sky_floors\sky_roof_mechanical.p3d";
	};
};
