// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Props
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Props_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_ReceptionDesk: Land_SKY_Props_Base
	{
		// 3 m lobby counter with return and monitor
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_receptiondesk.p3d";
	};
	class Land_SKY_Desk: Land_SKY_Props_Base
	{
		// 1.6 m office desk with monitor
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_desk.p3d";
	};
	class Land_SKY_Cubicle: Land_SKY_Props_Base
	{
		// 2 x 2 m workstation: 3 fabric screens + L desk
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_cubicle.p3d";
	};
	class Land_SKY_ServerRack: Land_SKY_Props_Base
	{
		// 42U server rack (closed, atlas front)
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_serverrack.p3d";
	};
	class Land_SKY_VendingMachine: Land_SKY_Props_Base
	{
		// drinks vending machine with openable pickup flap
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_vendingmachine.p3d";
		class Doors
		{
			class flap
			{
				displayName = "Pickup flap";
				component = "flap";
				soundPos = "flap_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class flap
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"flap"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_Locker: Land_SKY_Props_Base
	{
		// bank of 3 steel lockers, each door openable
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_locker.p3d";
		class Doors
		{
			class locker_door1
			{
				displayName = "Locker door";
				component = "locker_door1";
				soundPos = "locker_door1_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
			class locker_door2
			{
				displayName = "Locker door";
				component = "locker_door2";
				soundPos = "locker_door2_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
			class locker_door3
			{
				displayName = "Locker door";
				component = "locker_door3";
				soundPos = "locker_door3_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class locker_door1
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"locker_door1"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
				class locker_door2
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"locker_door2"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
				class locker_door3
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"locker_door3"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_Sofa: Land_SKY_Props_Base
	{
		// 2-seat fabric sofa
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_sofa.p3d";
	};
	class Land_SKY_Bed: Land_SKY_Props_Base
	{
		// single bed with headboard
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_bed.p3d";
	};
	class Land_SKY_Kitchenette: Land_SKY_Props_Base
	{
		// 1.8 m counter, sink, upper cabinets, fridge
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_kitchenette.p3d";
	};
	class Land_SKY_ExtinguisherCabinet: Land_SKY_Props_Base
	{
		// wall cabinet with extinguisher, openable glass door
		scope = 1;
		model = "SKY_Skyline\sky_props\sky_extinguishercabinet.p3d";
		class Doors
		{
			class cab_door
			{
				displayName = "Cabinet door";
				component = "cab_door";
				soundPos = "cab_door_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class cab_door
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"cab_door"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
};
