// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Roads
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Roads_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Viaduct_Straight: Land_SKY_Roads_Base
	{
		// elevated road, 12 m segment at 7 m, barriers, central pier
		scope = 1;
		model = "SKY_Skyline\sky_roads\sky_viaduct_straight.p3d";
	};
	class Land_SKY_Viaduct_Ramp: Land_SKY_Roads_Base
	{
		// viaduct ramp: 0 -> 7 m over 48 m, retaining walls
		scope = 1;
		model = "SKY_Skyline\sky_roads\sky_viaduct_ramp.p3d";
	};
	class Land_SKY_Tunnel_Straight: Land_SKY_Roads_Base
	{
		// cut-and-cover road tunnel, 12 m segment, earth berms, deck on top
		scope = 1;
		model = "SKY_Skyline\sky_roads\sky_tunnel_straight.p3d";
	};
	class Land_SKY_Tunnel_Portal: Land_SKY_Roads_Base
	{
		// tunnel end cell: headwall over the mouth at -Y, hazard band, sign
		scope = 1;
		model = "SKY_Skyline\sky_roads\sky_tunnel_portal.p3d";
	};
	class Land_SKY_Bridge_Long: Land_SKY_Roads_Base
	{
		// 96 m truss bridge: checkpoint, convoy pile-up, sniper nests (the bridge)
		scope = 1;
		model = "SKY_Skyline\sky_roads\sky_bridge_long.p3d";
	};
};
