// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_TowerA
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_TowerA_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_TowerA_Floor_Office: Land_SKY_TowerA_Base
	{
		scope = 1;
		model = "SKY_Skyline\sky_towera\sky_towera_floor_office.p3d";
	};
	class Land_SKY_TowerA_Roof_Helipad: Land_SKY_TowerA_Base
	{
		scope = 1;
		model = "SKY_Skyline\sky_towera\sky_towera_roof_helipad.p3d";
	};
	class Land_SKY_TowerA_Lobby: Land_SKY_TowerA_Base
	{
		scope = 1;
		model = "SKY_Skyline\sky_towera\sky_towera_lobby.p3d";
		class Doors
		{
			class door_sec
			{
				displayName = "Security door";
				component = "door_sec";
				soundPos = "door_sec_action";
				animPeriod = 1.0;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		// SKY keycard doors: Doors class names + required tier (read by script class Land_SKY_TowerA_Lobby).
		skyKeycardDoors[] = {"door_sec"};
		skyKeycardTiers[] = {2};
		skyKeycardRelockMs = 60000;
		// Security room interior, model space {x0, x1, z0, z1} (exit button works only inside).
		skySecurityRoom[] = {6.125, 11.85, 6.125, 11.85};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_sec
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_sec"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_TowerA_Core: Land_SKY_TowerA_Base
	{
		scope = 1;
		model = "SKY_Skyline\sky_towera\sky_towera_core.p3d";
		class AnimationSources
		{
			class elev_door_l0
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l1
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l2
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l3
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l4
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l5
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
			class elev_door_l6
			{
				source = "user";
				animPeriod = 1.2;
				initPhase = 0;
			};
		};
		// SKY elevator parameters (read by script class Land_SKY_TowerA_Core).
		skyStops[] = {0, 7, 10.5, 14, 17.5, 21, 24.5};
		skyMaxOccupants = 4;
		skyCooldownMs = 4000;
		skyDoorOpenMs = 8000;
		skyTravelMsBase = 1500;
		skyTravelMsPerStop = 500;
		skyCabHalfX = 1.25;
		skyCabHalfY = 1.375;
		skyCabHeight = 2.7;
		skyPanelReach = 1.6;
	};
};
