// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_CityCom
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_CityCom_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_City_CornerShop_Intact: Land_SKY_CityCom_Base
	{
		// corner bakery with two flats above, shopfront on two streets (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornershop_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerShop_Damaged: Land_SKY_CityCom_Base
	{
		// corner bakery with two flats above, shopfront on two streets (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornershop_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerShop_Ruined: Land_SKY_CityCom_Base
	{
		// corner bakery with two flats above, shopfront on two streets (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornershop_ruined.p3d";
	};
	class Land_SKY_City_OfficeMid_Intact: Land_SKY_CityCom_Base
	{
		// 6-storey glass office building, open plan with corner offices (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officemid_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeMid_Damaged: Land_SKY_CityCom_Base
	{
		// 6-storey glass office building, open plan with corner offices (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officemid_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeMid_Ruined: Land_SKY_CityCom_Base
	{
		// 6-storey glass office building, open plan with corner offices (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officemid_ruined.p3d";
	};
	class Land_SKY_City_CornerPharmacy_Intact: Land_SKY_CityCom_Base
	{
		// corner pharmacy with two flats above (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerpharmacy_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerPharmacy_Damaged: Land_SKY_CityCom_Base
	{
		// corner pharmacy with two flats above (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerpharmacy_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerPharmacy_Ruined: Land_SKY_CityCom_Base
	{
		// corner pharmacy with two flats above (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerpharmacy_ruined.p3d";
	};
	class Land_SKY_City_CornerHardware_Intact: Land_SKY_CityCom_Base
	{
		// corner hardware store with two flats above (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerhardware_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerHardware_Damaged: Land_SKY_CityCom_Base
	{
		// corner hardware store with two flats above (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerhardware_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CornerHardware_Ruined: Land_SKY_CityCom_Base
	{
		// corner hardware store with two flats above (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cornerhardware_ruined.p3d";
	};
	class Land_SKY_City_OfficeTall_Intact: Land_SKY_CityCom_Base
	{
		// 9-storey glass office building (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officetall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeTall_Damaged: Land_SKY_CityCom_Base
	{
		// 9-storey glass office building (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officetall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_OfficeTall_Ruined: Land_SKY_CityCom_Base
	{
		// 9-storey glass office building (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_officetall_ruined.p3d";
	};
	class Land_SKY_City_ShopRow_Intact: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: cafe below, three flats (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprow_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRow_Damaged: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: cafe below, three flats (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprow_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRow_Ruined: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: cafe below, three flats (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprow_ruined.p3d";
	};
	class Land_SKY_City_Supermarket_Intact: Land_SKY_CityCom_Base
	{
		// single-storey supermarket: aisles, checkouts, stock room (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarket_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Supermarket_Damaged: Land_SKY_CityCom_Base
	{
		// single-storey supermarket: aisles, checkouts, stock room (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarket_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Supermarket_Ruined: Land_SKY_CityCom_Base
	{
		// single-storey supermarket: aisles, checkouts, stock room (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarket_ruined.p3d";
	};
	class Land_SKY_City_ShopRowMarket_Intact: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: grocer below (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowmarket_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowMarket_Damaged: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: grocer below (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowmarket_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowMarket_Ruined: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: grocer below (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowmarket_ruined.p3d";
	};
	class Land_SKY_City_ShopRowNews_Intact: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: newsagent below (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprownews_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowNews_Damaged: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: newsagent below (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprownews_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowNews_Ruined: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: newsagent below (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprownews_ruined.p3d";
	};
	class Land_SKY_City_ShopRowHardware_Intact: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: hardware store below (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowhardware_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowHardware_Damaged: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: hardware store below (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowhardware_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShopRowHardware_Ruined: Land_SKY_CityCom_Base
	{
		// 4-storey terrace: hardware store below (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_shoprowhardware_ruined.p3d";
	};
	class Land_SKY_City_SupermarketSmall_Intact: Land_SKY_CityCom_Base
	{
		// small supermarket (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarketsmall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_SupermarketSmall_Damaged: Land_SKY_CityCom_Base
	{
		// small supermarket (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarketsmall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_SupermarketSmall_Ruined: Land_SKY_CityCom_Base
	{
		// small supermarket (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_supermarketsmall_ruined.p3d";
	};
	class Land_SKY_City_GasStation_Intact: Land_SKY_CityCom_Base
	{
		// filling station: shop and pump canopy on the forecourt (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_gasstation_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_GasStation_Damaged: Land_SKY_CityCom_Base
	{
		// filling station: shop and pump canopy on the forecourt (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_gasstation_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_GasStation_Ruined: Land_SKY_CityCom_Base
	{
		// filling station: shop and pump canopy on the forecourt (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_gasstation_ruined.p3d";
	};
	class Land_SKY_City_Cafe_Intact: Land_SKY_CityCom_Base
	{
		// cafe pavilion with a street terrace (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafe_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Cafe_Damaged: Land_SKY_CityCom_Base
	{
		// cafe pavilion with a street terrace (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafe_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Cafe_Ruined: Land_SKY_CityCom_Base
	{
		// cafe pavilion with a street terrace (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafe_ruined.p3d";
	};
	class Land_SKY_City_Bank_Intact: Land_SKY_CityCom_Base
	{
		// 3-storey stone bank: banking hall, vault, offices above (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bank_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Bank_Damaged: Land_SKY_CityCom_Base
	{
		// 3-storey stone bank: banking hall, vault, offices above (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bank_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Bank_Ruined: Land_SKY_CityCom_Base
	{
		// 3-storey stone bank: banking hall, vault, offices above (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bank_ruined.p3d";
	};
	class Land_SKY_City_DepartmentStore_Intact: Land_SKY_CityCom_Base
	{
		// 3-storey department store round a central atrium (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_departmentstore_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_DepartmentStore_Damaged: Land_SKY_CityCom_Base
	{
		// 3-storey department store round a central atrium (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_departmentstore_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_DepartmentStore_Ruined: Land_SKY_CityCom_Base
	{
		// 3-storey department store round a central atrium (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_departmentstore_ruined.p3d";
	};
	class Land_SKY_City_CafeBrick_Intact: Land_SKY_CityCom_Base
	{
		// brick cafe pavilion with a street terrace (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafebrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CafeBrick_Damaged: Land_SKY_CityCom_Base
	{
		// brick cafe pavilion with a street terrace (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafebrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_CafeBrick_Ruined: Land_SKY_CityCom_Base
	{
		// brick cafe pavilion with a street terrace (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_cafebrick_ruined.p3d";
	};
	class Land_SKY_City_Bar_Intact: Land_SKY_CityCom_Base
	{
		// corner bar: long counter, bottle wall, booths, pool table (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bar_intact.p3d";
		skySearch = "alcohol";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Bar_Damaged: Land_SKY_CityCom_Base
	{
		// corner bar: long counter, bottle wall, booths, pool table (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bar_damaged.p3d";
		skySearch = "alcohol";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Bar_Ruined: Land_SKY_CityCom_Base
	{
		// corner bar: long counter, bottle wall, booths, pool table (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_com\sky_city_bar_ruined.p3d";
		skySearch = "alcohol";
	};
};
