// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_CityEnv
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_CityEnv_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_City_RubbleLot_A: Land_SKY_CityEnv_Base
	{
		// 12 x 12 m collapsed building lot
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_rubblelot_a.p3d";
	};
	class Land_SKY_City_RubbleLot_B: Land_SKY_CityEnv_Base
	{
		// 12 x 12 m collapsed building lot
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_rubblelot_b.p3d";
	};
	class Land_SKY_City_RubbleLot_C: Land_SKY_CityEnv_Base
	{
		// 12 x 12 m collapsed building lot
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_rubblelot_c.p3d";
	};
	class Land_SKY_City_RubbleLot_D: Land_SKY_CityEnv_Base
	{
		// 12 x 12 m collapsed building lot
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_rubblelot_d.p3d";
	};
	class Land_SKY_City_WaterTower: Land_SKY_CityEnv_Base
	{
		// 18 m steel water tower on a lattice frame
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_watertower.p3d";
	};
	class Land_SKY_City_MetroEntrance_A: Land_SKY_CityEnv_Base
	{
		// metro stair head sealed with steel plates, railings, sign
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_metroentrance_a.p3d";
	};
	class Land_SKY_City_MetroEntrance_B: Land_SKY_CityEnv_Base
	{
		// glazed metro entrance pavilion, doors chained shut
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_city_metroentrance_b.p3d";
	};
	class Land_SKY_Veg_Weeds: Land_SKY_CityEnv_Base
	{
		// 3 x 3 m patch of grass, weeds, burdock and bramble (no collision)
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_veg_weeds.p3d";
	};
	class Land_SKY_Veg_Bush: Land_SKY_CityEnv_Base
	{
		// 2.5 m wild shrub with bramble skirt (no collision)
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_veg_bush.p3d";
	};
	class Land_SKY_Veg_Birch: Land_SKY_CityEnv_Base
	{
		// 9 m self-seeded birch: trunk collides, crown cards
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_veg_birch.p3d";
	};
	class Land_SKY_Veg_TreeDead: Land_SKY_CityEnv_Base
	{
		// 6 m dead tree: trunk collides, bare branch cards
		scope = 1;
		model = "SKY_Skyline\sky_city_env\sky_veg_treedead.p3d";
	};
};
