// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_CityInd
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_CityInd_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_City_Warehouse_Intact: Land_SKY_CityInd_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouse_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Warehouse_Damaged: Land_SKY_CityInd_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouse_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Warehouse_Ruined: Land_SKY_CityInd_Base
	{
		// single-bay steel warehouse, 2 roller doors, racks and a site office (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouse_ruined.p3d";
	};
	class Land_SKY_City_WarehouseSmall_Intact: Land_SKY_CityInd_Base
	{
		// small steel warehouse, 1 roller door (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehousesmall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseSmall_Damaged: Land_SKY_CityInd_Base
	{
		// small steel warehouse, 1 roller door (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehousesmall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseSmall_Ruined: Land_SKY_CityInd_Base
	{
		// small steel warehouse, 1 roller door (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehousesmall_ruined.p3d";
	};
	class Land_SKY_City_Workshop_Intact: Land_SKY_CityInd_Base
	{
		// car repair workshop: roller door, workbench, shelving (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshop_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Workshop_Damaged: Land_SKY_CityInd_Base
	{
		// car repair workshop: roller door, workbench, shelving (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshop_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Workshop_Ruined: Land_SKY_CityInd_Base
	{
		// car repair workshop: roller door, workbench, shelving (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshop_ruined.p3d";
	};
	class Land_SKY_City_GarageBlock_Intact: Land_SKY_CityInd_Base
	{
		// row of lock-up garages, two shutters open (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_garageblock_intact.p3d";
	};
	class Land_SKY_City_GarageBlock_Damaged: Land_SKY_CityInd_Base
	{
		// row of lock-up garages, two shutters open (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_garageblock_damaged.p3d";
	};
	class Land_SKY_City_GarageBlock_Ruined: Land_SKY_CityInd_Base
	{
		// row of lock-up garages, two shutters open (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_garageblock_ruined.p3d";
	};
	class Land_SKY_City_Kiosk_Intact: Land_SKY_CityInd_Base
	{
		// news kiosk (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kiosk_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Kiosk_Damaged: Land_SKY_CityInd_Base
	{
		// news kiosk (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kiosk_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Kiosk_Ruined: Land_SKY_CityInd_Base
	{
		// news kiosk (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kiosk_ruined.p3d";
	};
	class Land_SKY_City_Shed_Intact: Land_SKY_CityInd_Base
	{
		// yard shed (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shed_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Shed_Damaged: Land_SKY_CityInd_Base
	{
		// yard shed (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shed_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Shed_Ruined: Land_SKY_CityInd_Base
	{
		// yard shed (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shed_ruined.p3d";
	};
	class Land_SKY_City_WorkshopBrick_Intact: Land_SKY_CityInd_Base
	{
		// brick car repair workshop (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshopbrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WorkshopBrick_Damaged: Land_SKY_CityInd_Base
	{
		// brick car repair workshop (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshopbrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WorkshopBrick_Ruined: Land_SKY_CityInd_Base
	{
		// brick car repair workshop (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_workshopbrick_ruined.p3d";
	};
	class Land_SKY_City_KioskCafe_Intact: Land_SKY_CityInd_Base
	{
		// coffee kiosk (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kioskcafe_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_KioskCafe_Damaged: Land_SKY_CityInd_Base
	{
		// coffee kiosk (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kioskcafe_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_KioskCafe_Ruined: Land_SKY_CityInd_Base
	{
		// coffee kiosk (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_kioskcafe_ruined.p3d";
	};
	class Land_SKY_City_ShedBrick_Intact: Land_SKY_CityInd_Base
	{
		// brick yard shed (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shedbrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShedBrick_Damaged: Land_SKY_CityInd_Base
	{
		// brick yard shed (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shedbrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_ShedBrick_Ruined: Land_SKY_CityInd_Base
	{
		// brick yard shed (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_shedbrick_ruined.p3d";
	};
	class Land_SKY_City_WarehouseLarge_Intact: Land_SKY_CityInd_Base
	{
		// large steel warehouse, 3 roller doors (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouselarge_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseLarge_Damaged: Land_SKY_CityInd_Base
	{
		// large steel warehouse, 3 roller doors (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouselarge_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_WarehouseLarge_Ruined: Land_SKY_CityInd_Base
	{
		// large steel warehouse, 3 roller doors (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_warehouselarge_ruined.p3d";
	};
	class Land_SKY_City_FactoryHall_Intact: Land_SKY_CityInd_Base
	{
		// brick factory hall: sawtooth roof, machines, crane beam (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_factoryhall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_FactoryHall_Damaged: Land_SKY_CityInd_Base
	{
		// brick factory hall: sawtooth roof, machines, crane beam (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_factoryhall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_FactoryHall_Ruined: Land_SKY_CityInd_Base
	{
		// brick factory hall: sawtooth roof, machines, crane beam (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_factoryhall_ruined.p3d";
	};
	class Land_SKY_City_ParkingGarage_Intact: Land_SKY_CityInd_Base
	{
		// 4-deck open parking garage: car ramps, stair, wrecks (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_parkinggarage_intact.p3d";
	};
	class Land_SKY_City_ParkingGarage_Damaged: Land_SKY_CityInd_Base
	{
		// 4-deck open parking garage: car ramps, stair, wrecks (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_parkinggarage_damaged.p3d";
	};
	class Land_SKY_City_ParkingGarage_Ruined: Land_SKY_CityInd_Base
	{
		// 4-deck open parking garage: car ramps, stair, wrecks (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_parkinggarage_ruined.p3d";
	};
	class Land_SKY_City_Substation_Intact: Land_SKY_CityInd_Base
	{
		// fenced electrical substation (not enterable) (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_substation_intact.p3d";
	};
	class Land_SKY_City_Substation_Damaged: Land_SKY_CityInd_Base
	{
		// fenced electrical substation (not enterable) (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_substation_damaged.p3d";
	};
	class Land_SKY_City_Substation_Ruined: Land_SKY_CityInd_Base
	{
		// fenced electrical substation (not enterable) (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_ind\sky_city_substation_ruined.p3d";
	};
};
