#!/usr/bin/env python3
"""Generate SKY_Skyline Central Economy files from assets/skyspec.py.

    python mods/SKY_Skyline/economy/gen_economy.py [--check]

Writes (committed, reviewable):
  sky_ce/types.xml              keycards           -> <ce folder="sky_ce"> (cfgeconomycore)
  sky_ce/cfgspawnabletypes.xml  keycard wear range -> <ce folder="sky_ce">
  sky_ce/events.xml             StaticSKYRoofDrop  -> <ce folder="sky_ce">
  cfgeconomycore_snippet.xml    the <ce folder> block to add to the mission's cfgeconomycore.xml
  mapgroupproto_sky.xml         loot groups per module - MERGE into the mission mapgroupproto.xml
                                (mapgroupproto is not loadable through <ce folder>)
Formats verified against BohemiaInteractive/DayZ-Central-Economy (dayzOffline.chernarusplus):
mapgroupproto group/usage/container/category/tag/point, types.xml type fields,
StaticAirplaneCrate event (supply boxes) and cfgspawnabletypes <damage min max>.
Placement-dependent files (cfgeventspawns positions, mapgrouppos) come from
placement/sky_layout.py and the in-game survey/export.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "assets"))
import skyspec as S  # noqa: E402

HEAD = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<!-- GENERATED by economy/gen_economy.py from assets/skyspec.py -->\n'

# Keycards: balance vs vanilla references (NVGoggles nominal 5/min 3 Military; Paper 0).
KEYCARDS = {
    1: {"nominal": 10, "min": 5, "lifetime": 14400, "usages": ["Office", "Town"], "values": []},
    2: {"nominal": 4, "min": 2, "lifetime": 14400, "usages": ["Office", "Police"], "values": ["Tier2", "Tier3"]},
    3: {"nominal": 1, "min": 0, "lifetime": 28800, "usages": ["Military"], "values": ["Tier4"]},
}


def types_xml():
    out = HEAD + "<types>\n"
    for tier, name in S.KEYCARD_TIERS.items():
        k = KEYCARDS[tier]
        out += '    <type name="%s">\n' % name
        out += "        <nominal>%d</nominal>\n        <lifetime>%d</lifetime>\n        <restock>0</restock>\n" % (k["nominal"], k["lifetime"])
        out += "        <min>%d</min>\n        <quantmin>-1</quantmin>\n        <quantmax>-1</quantmax>\n        <cost>100</cost>\n" % k["min"]
        out += '        <flags count_in_cargo="0" count_in_hoarder="0" count_in_map="1" count_in_player="1" crafted="0" deloot="0"/>\n'
        out += '        <category name="tools"/>\n'
        out += "".join('        <usage name="%s"/>\n' % u for u in k["usages"])
        out += "".join('        <value name="%s"/>\n' % v for v in k["values"])
        out += "    </type>\n"
    # The tower modules are spawned by objectSpawnersArr, not by CE: no types entries for them.
    return out + "</types>\n"


def spawnable_xml():
    out = HEAD + "<spawnabletypes>\n"
    for tier, name in S.KEYCARD_TIERS.items():
        out += '    <type name="%s">\n        <damage min="0.0" max="%.2f" />\n    </type>\n' % (name, 0.3 if tier < 3 else 0.1)
    return out + "</spawnabletypes>\n"


def events_xml():
    # Same shape as vanilla StaticAirplaneCrate (fixed positions, supply-box children with loot).
    return HEAD + """<events>
    <event name="StaticSKYRoofDrop">
        <nominal>1</nominal>
        <min>0</min>
        <max>0</max>
        <lifetime>2700</lifetime>
        <restock>0</restock>
        <saferadius>200</saferadius>
        <distanceradius>1</distanceradius>
        <cleanupradius>300</cleanupradius>
        <flags deletable="1" init_random="0" remove_damaged="0"/>
        <position>fixed</position>
        <limit>child</limit>
        <active>1</active>
        <children>
            <child lootmax="6" lootmin="3" max="1" min="1" type="StaticObj_Misc_SupplyBox1_DE"/>
            <child lootmax="6" lootmin="3" max="1" min="1" type="StaticObj_Misc_SupplyBox2_DE"/>
        </children>
    </event>
</events>
"""


def core_snippet():
    return """<!-- Add inside <economycore> of the mission's cfgeconomycore.xml; copy economy/sky_ce/ to <mission>/sky_ce/ -->
<ce folder="sky_ce">
    <file name="types.xml" type="types" />
    <file name="cfgspawnabletypes.xml" type="spawnabletypes" />
    <file name="events.xml" type="events" />
</ce>
"""


def proto_xml():
    out = HEAD + "<!-- MERGE these <group> blocks into the mission's mapgroupproto.xml (inside <prototype>). -->\n<prototype>\n"
    for cls, g in S.LOOT.items():
        out += '    <group name="%s" lootmax="%d">\n' % (cls, g["lootmax"])
        out += "".join('        <usage name="%s" />\n' % u for u in g["usages"])
        for c in g["containers"]:
            out += '        <container name="%s" lootmax="%d">\n' % (c["name"], c["lootmax"])
            out += "".join('            <category name="%s" />\n' % x for x in c["categories"])
            out += "".join('            <tag name="%s" />\n' % x for x in c["tags"])
            for p in c["points"]:
                # model space: x = Blender X, y = height above the origin (slab top), z = Blender Y.
                # (x, y) = floor point with LOOT_POINT range/height; (x, y, z, range, height) =
                # furniture surface point (vanilla "lootshelves" pattern, batch 5 props).
                x, y = p[0], p[1]
                z, rng, h = (p[2], p[3], p[4]) if len(p) == 5 else (0.0, S.LOOT_POINT["range"], S.LOOT_POINT["height"])
                out += '            <point pos="%.6f %.6f %.6f" range="%.6f" height="%.6f" />\n' % (x, z, y, rng, h)
            out += "        </container>\n"
        out += "    </group>\n"
    return out + "</prototype>\n"


def outputs():
    return {
        "sky_ce/types.xml": types_xml(),
        "sky_ce/cfgspawnabletypes.xml": spawnable_xml(),
        "sky_ce/events.xml": events_xml(),
        "cfgeconomycore_snippet.xml": core_snippet(),
        "mapgroupproto_sky.xml": proto_xml(),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    for rel, text in outputs().items():
        p = os.path.join(HERE, rel)
        cur = open(p).read() if os.path.exists(p) else None
        if cur != text:
            stale.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                open(p, "w").write(text)
    if a.check and stale:
        sys.exit("stale: " + ", ".join(stale))
    print("up to date" if not stale else "wrote: " + ", ".join(stale))


if __name__ == "__main__":
    main()
