// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Items
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Gear_Drinks", "DZ_Gear_Camping", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class Inventory_Base;
	class SKY_Keycard_Base: Inventory_Base
	{
		scope = 0;
		displayName = "Access keycard";
		descriptionShort = "Magnetic access card for Skyline building security doors.";
		model = "SKY_Skyline\sky_items\sky_keycard.p3d";
		weight = 10;
		itemSize[] = {1, 1};
		rotationFlags = 17;
		hiddenSelections[] = {"camo"};
		skyTier = 0;
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 100;
					healthLevels[] =
					{
						{1.0, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.7, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.5, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.3, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.0, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}}
					};
				};
			};
		};
	};
	class SKY_Keycard_T1: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 1)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t1_co.paa"};
		skyTier = 1;
	};
	class SKY_Keycard_T2: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 2)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t2_co.paa"};
		skyTier = 2;
	};
	class SKY_Keycard_T3: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 3)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t3_co.paa"};
		skyTier = 3;
	};
	class SeaChest;
	class SKY_Kennel: SeaChest
	{
		scope = 2;
		displayName = "Dog kennel";
		descriptionShort = "A doghouse and its old guard dog. Place it by your stash: while you are away the dog keeps everyone out of it and barks at anyone who comes close.";
		model = "SKY_Skyline\sky_items\sky_kennel.p3d";
		weight = 18000;
		itemSize[] = {10, 10};
		itemsCargoSize[] = {10, 6};
		canBeDigged = 0;
	};
	class GlassBottle;
	class SKY_Bottle_Beer: GlassBottle
	{
		scope = 2;
		displayName = "Bottle of beer";
		descriptionShort = "Warm, flat lager from a looted bar. Mild.";
		varLiquidTypeInit = 4096;
		varQuantityInit = 500;
	};
	class SKY_Bottle_Vodka: GlassBottle
	{
		scope = 2;
		displayName = "Bottle of vodka";
		descriptionShort = "Cheap Chernarussian vodka. A shot dulls pain; half a bottle and the street starts to spin.";
		varLiquidTypeInit = 2048;
		varQuantityInit = 500;
	};
};
