// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Items
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class Inventory_Base;
	class SKY_Keycard_Base: Inventory_Base
	{
		scope = 0;
		displayName = "Access keycard";
		descriptionShort = "Magnetic access card for Skyline building security doors.";
		model = "SKY_Skyline\sky_items\sky_keycard.p3d";
		weight = 10;
		itemSize[] = {1, 1};
		rotationFlags = 17;
		hiddenSelections[] = {"camo"};
		skyTier = 0;
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 100;
					healthLevels[] =
					{
						{1.0, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.7, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.5, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.3, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}},
						{0.0, {"SKY_Skyline\sky_items\data\sky_keycard.rvmat"}}
					};
				};
			};
		};
	};
	class SKY_Keycard_T1: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 1)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t1_co.paa"};
		skyTier = 1;
	};
	class SKY_Keycard_T2: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 2)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t2_co.paa"};
		skyTier = 2;
	};
	class SKY_Keycard_T3: SKY_Keycard_Base
	{
		scope = 2;
		displayName = "Access keycard (level 3)";
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_items\data\sky_keycard_t3_co.paa"};
		skyTier = 3;
	};
};
