"""Generate CITY_PLAN.md: the full-city building estimate and live progress (D56).

    python assets/city_progress.py [--check]

Reads skyspec.CITY_CATALOG (what a full SKY city needs), skyspec.CITY_ARCHETYPES (what the
procedural generator can build) and the P3Ds on disk (what is built). --check exits 1 if the
committed CITY_PLAN.md is stale. Status per type:
  planned            nothing built
  in progress        some variants built
  built-unverified   every variant built, not yet tested in DayZ
  tested             listed in skyspec.CITY_TESTED after the TESTING.md rows passed
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import skyspec as S  # noqa: E402

MOD = os.path.dirname(HERE)
OUT = os.path.join(MOD, "CITY_PLAN.md")


def built_variants():
    """catalog id -> list of built archetype names (all 3 ruin states exported)."""
    out = {}
    for a, A in S.CITY_ARCHETYPES.items():
        cid = A.get("catalog", a)
        p3ds = [S.KIT["City_%s_%s" % (a, st)] for st in S.RUIN_STATES]
        if all(os.path.exists(os.path.join(MOD, "addons", e["pbo"], e["p3d"])) for e in p3ds):
            out.setdefault(cid, []).append(a)
    return out


def kit_built(cid):
    """Kit pieces registered with KIT[...]["catalog"] = cid (e.g. rubble lots) whose P3D exists."""
    return sum(1 for e in S.KIT.values() if e.get("catalog") == cid
               and os.path.exists(os.path.join(MOD, "addons", e["pbo"], e["p3d"])))


def modular_built(cid):
    if cid in ("TowerOffice", "TowerResidential"):
        need = [S.P3D[S.CLASS_LOBBY], S.P3D[S.CLASS_FLOOR], S.P3D[S.CLASS_CORE]]
        ok = all(os.path.exists(os.path.join(MOD, "addons", "sky_towera", n)) for n in need)
        if cid == "TowerResidential":
            ok = ok and os.path.exists(os.path.join(MOD, "addons", "sky_floors", S.KIT["Floor_Apartments"]["p3d"]))
        return 1 if ok else 0
    return 0


def render():
    bv = built_variants()
    tested = set(getattr(S, "CITY_TESTED", ()))
    rows, tot = [], {"types": 0, "types_started": 0, "var": 0, "var_built": 0, "models": 0, "models_built": 0,
                     "inst": 0, "inst_cov": 0}
    for (cid, group, size, floors, kind, variants, inst, wave, note) in S.CITY_CATALOG:
        states = 3 if kind == "proc" else 1
        nb = len(bv.get(cid, [])) if kind == "proc" else (modular_built(cid) or kit_built(cid))
        nb = min(nb, variants)
        status = ("tested" if cid in tested else "built-unverified") if nb >= variants else ("in progress" if nb else "planned")
        tot["types"] += 1
        tot["types_started"] += 1 if nb else 0
        tot["var"] += variants
        tot["var_built"] += nb
        tot["models"] += variants * states
        tot["models_built"] += nb * states
        tot["inst"] += inst
        tot["inst_cov"] += inst if nb else 0
        rows.append("| %s | %s | %s | %s | %s | %d / %d | %d / %d | %d | %d | %s | %s |" % (
            cid, group, size, floors or "-", kind, nb, variants, nb * states, variants * states, inst, wave, status, note))

    def pct(a, b):
        return "%d %%" % round(100.0 * a / b) if b else "-"
    bar_n = int(round(20.0 * tot["models_built"] / tot["models"]))
    lines = [
        "# SKY city: building estimate and progress",
        "",
        "GENERATED by `assets/city_progress.py` from `skyspec.CITY_CATALOG` / `CITY_ARCHETYPES` and the P3Ds on",
        "disk - do not edit by hand; change the catalog and re-run (`--check` in the gates).",
        "",
        "## Estimate (how many buildings a full city needs)",
        "",
        "Reference, counted from the vanilla Central Economy (`dayzOffline.chernarusplus`): **414** lootable",
        "building types on the whole map; **Chernogorsk** has ~980 lootable buildings of **169** types,",
        "Elektrozavodsk ~545 of 136. The target SKY city (dense downtown, midtown, two residential districts,",
        "an industrial edge) is Chernogorsk-sized:",
        "",
        "| | Target |",
        "|---|---|",
        "| building types | %d |" % tot["types"],
        "| type variants (size / layout / skin) | %d |" % tot["var"],
        "| unique building models (procedural types x 3 ruin states + modular / kit) | **%d** |" % tot["models"],
        "| placed buildings in the full city | **%d** |" % tot["inst"],
        "| plus: street kit, props, decals (sky_street / sky_props) | 39 kit models, built |",
        "",
        "Ruin mix for placement (seeded per lot): ~45 % intact, ~35 % damaged, ~20 % ruined; ruined",
        "lots concentrate along the 'front line' streets, intact ones in the residential districts.",
        "",
        "## Progress",
        "",
        "`[%s%s]` %s of the unique models" % ("#" * bar_n, "." * (20 - bar_n), pct(tot["models_built"], tot["models"])),
        "",
        "| | Built | Target | % |",
        "|---|---|---|---|",
        "| building types started | %d | %d | %s |" % (tot["types_started"], tot["types"], pct(tot["types_started"], tot["types"])),
        "| type variants | %d | %d | %s |" % (tot["var_built"], tot["var"], pct(tot["var_built"], tot["var"])),
        "| unique models | %d | %d | %s |" % (tot["models_built"], tot["models"], pct(tot["models_built"], tot["models"])),
        "| placed buildings a generator could fill today (one variant per type repeated) | %d | %d | %s |" % (
            tot["inst_cov"], tot["inst"], pct(tot["inst_cov"], tot["inst"])),
        "",
        "Nothing has run in DayZ yet: every built model is `built-unverified` until its TESTING.md rows pass",
        "and its id is added to `skyspec.CITY_TESTED`.",
        "",
        "## Catalog",
        "",
        "kind: `proc` = procedural archetype (`build_city.py`, 3 ruin states each), `modular` = Tower A",
        "system, `kit` = small piece. Wave = planned production batch (0 = existing, 1 = this batch).",
        "",
        "| Type | Group | Footprint (m) | Floors | Kind | Variants built | Models built | Placed | Wave | Status | Note |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ] + rows + [
        "",
        "## Waves",
        "",
        "| Wave | Content | Models |",
        "|---|---|---|",
    ]
    for w in sorted({e[7] for e in S.CITY_CATALOG}):
        es = [e for e in S.CITY_CATALOG if e[7] == w]
        lines.append("| %d | %s | %d |" % (w, ", ".join(e[0] for e in es), sum(e[5] * (3 if e[4] == "proc" else 1) for e in es)))
    lines += [
        "",
        "## Adding a building",
        "",
        "1. Add the archetype to `skyspec.CITY_ARCHETYPES` (footprint, levels with their use, skin, stair,",
        "   door bay, sign, loot); a size / skin variant of an existing type sets `\"catalog\": \"<type>\"`.",
        "   New uses need a floor plan in `build_city.layout()`; everything else (facades, stairs, ruins,",
        "   interiors, doors, loot, lights) comes from the shared grammar, so the style stays coherent.",
        "2. `blender ... -P assets/blender/build_city.py -- --out addons` (exports 3 ruin states, loot JSON),",
        "   `test_city.py`, `gen_configs.py`, `gen_manifest.py`, `economy/gen_economy.py`, `check_assets.py`.",
        "3. `python assets/city_progress.py` (this file), then the gates and the TESTING.md rows.",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
    if a.check:
        if cur != text:
            print("CITY_PLAN.md is stale - run python assets/city_progress.py")
            sys.exit(1)
        print("up to date")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
