#!/usr/bin/env python3
"""Generate config.cpp / model.cfg / rvmat files for SKY_Skyline from skyspec.

    python mods/SKY_Skyline/assets/gen_configs.py            # writes into addons/
    python mods/SKY_Skyline/assets/gen_configs.py --check    # exit 1 if files are stale

Outputs are committed (reviewable diffs); re-run after editing skyspec.py.
Syntax follows Bohemia's DayZ-Samples (Test_Building config.cpp/model.cfg,
Test_ClothingRetexture hiddenSelections) - see SLICE_REPORT.md for sources.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import skyspec as S  # noqa: E402

ADDONS = os.path.join(os.path.dirname(HERE), "addons")
HEADER = "// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.\n"


def patches(name, required):
    req = ", ".join('"%s"' % r for r in required)
    return ("class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[] = {};\n\t\tweapons[] = {};\n"
            "\t\trequiredVersion = 0.1;\n\t\trequiredAddons[] = {%s};\n\t};\n};\n" % (name, req))


# ------------------------------------------------------------------ rvmat
UVT = ("\tclass uvTransform\n\t{\n\t\taside[] = {1, 0, 0};\n\t\tup[] = {0, 1, 0};\n"
       "\t\tdir[] = {0, 0, 1};\n\t\tpos[] = {0, 0, 0};\n\t};\n")


def stage(n, texture, uv_source="tex", extra=""):
    body = '\ttexture = "%s";\n\tuvSource = "%s";\n' % (texture, uv_source)
    if uv_source == "tex":
        body += UVT
    return "class Stage%d\n{\n%s%s};\n" % (n, body, extra)


PROC = {"nohq": "#(argb,8,8,3)color(0.5,0.5,1,1,NOHQ)", "as": "#(argb,8,8,3)color(1,1,1,1,AS)",
        "smdi": "#(argb,8,8,3)color(1,0.3,0.4,1,SMDI)"}
# Kit materials whose maps carry no information use procedural stages instead of
# files (perf batch-1 M5). Tower A's rvmats are left exactly as validated.
PROCEDURAL_MAPS = {
    "sky_roadmark": ("nohq", "as", "smdi"), "sky_foliage": ("nohq", "as", "smdi"),
    "sky_atlas": ("nohq", "as", "smdi"), "sky_billboard": ("nohq", "as", "smdi"), "sky_rust": ("as",),
    "sky_decal_dirt": ("nohq", "as", "smdi"), "sky_decal_cracks": ("nohq", "as", "smdi"),
    "sky_decal_graffiti": ("nohq", "as", "smdi"), "sky_windows": ("nohq", "as", "smdi"),
    "sky_brick": ("as", "smdi"), "sky_concpanel": ("as", "smdi"),          # perf batch-2 M1
    "sky_wood": ("nohq", "as", "smdi"), "sky_fabric": ("as", "smdi"),          # wood nohq: perf batch-3 L4
    "sky_ceiling": ("as", "smdi"),                                             # D53
    "sky_paint": ("as", "smdi"), "sky_textile": ("as", "smdi"), "sky_parquet": ("as",),   # D55
    "sky_render": ("as", "smdi"), "sky_rubble": ("as",), "sky_signs": ("nohq", "as", "smdi"),   # D56
    "sky_decal_grime": ("nohq", "as", "smdi"), "sky_vegetation": ("nohq", "as", "smdi"),          # D59
    "sky_wall_brick": ("as", "smdi"), "sky_wall_panel": ("as", "smdi"), "sky_wall_limestone": ("as", "smdi"),
    "sky_wall_render_cream": ("nohq", "as", "smdi"), "sky_wall_render_ochre": ("nohq", "as", "smdi"),
    "sky_wall_render_grey": ("nohq", "as", "smdi"), "sky_wall_render_white": ("nohq", "as", "smdi"),
}
# Constant specular/gloss for procedural _smdi stages (default PROC["smdi"] otherwise).
PROC_SMDI = {"sky_wall_brick": (0.08, 0.15), "sky_wall_panel": (0.1, 0.2), "sky_wall_limestone": (0.12, 0.2),
             "sky_wall_render_cream": (0.05, 0.1), "sky_wall_render_ochre": (0.05, 0.1), "sky_wall_render_grey": (0.05, 0.1),
             "sky_wall_render_white": (0.05, 0.1), "sky_decal_grime": (0.02, 0.05), "sky_vegetation": (0.08, 0.15), "sky_render": (0.05, 0.1), "sky_signs": (0.3, 0.4), "sky_paint": (0.06, 0.12), "sky_textile": (0.02, 0.05), "sky_ceiling": (0.05, 0.1), "sky_brick": (0.08, 0.15), "sky_concpanel": (0.1, 0.2), "sky_wood": (0.25, 0.35), "sky_fabric": (0.03, 0.1)}


def rvmat_super(base, spec_power=40, emissive=(0, 0, 0)):
    """Standard 'Super' shader layout (Stage1 nohq, 2 detail, 3 macro, 4 as,
    5 smdi, 6 fresnel, 7 env). Detail/macro are neutral procedurals."""
    d = S.PREFIX_TEX + "\\data\\" + base
    out = HEADER
    out += "ambient[] = {1, 1, 1, 1};\ndiffuse[] = {1, 1, 1, 1};\nforcedDiffuse[] = {0, 0, 0, 0};\n"
    out += "emmisive[] = {%g, %g, %g, 1};\nspecular[] = {0.7, 0.7, 0.7, 1};\nspecularPower = %d;\n" % (
        emissive + (spec_power,))
    out += 'PixelShaderID = "Super";\nVertexShaderID = "Super";\n'
    proc = PROCEDURAL_MAPS.get(base, ())

    def pick(m):
        if m not in proc:
            return d + "_%s.paa" % m
        if m == "smdi" and base in PROC_SMDI:
            return "#(argb,8,8,3)color(1,%g,%g,1,SMDI)" % PROC_SMDI[base]
        return PROC[m]
    out += stage(1, pick("nohq"))
    out += stage(2, "#(argb,8,8,3)color(0.5,0.5,0.5,1,DT)")
    out += stage(3, "#(argb,8,8,3)color(0,0,0,0,MC)")
    out += stage(4, pick("as"))
    out += stage(5, pick("smdi"))
    out += stage(6, "#(ai,64,64,1)fresnel(1.5,0.8)", "none")
    # Env map path follows the vanilla convention; confirmed by Check-SkyAssets.ps1 on P:.
    out += stage(7, S.ENV_MAP, "none", '\tuseWorldEnvMap = "true";\n')
    return out


def rvmat_flat(emissive=(0, 0, 0), color_stage=None):
    """Procedural-only Super rvmat (no texture files): lamps and other flat glowing parts."""
    out = HEADER
    out += "ambient[] = {1, 1, 1, 1};\ndiffuse[] = {1, 1, 1, 1};\nforcedDiffuse[] = {0, 0, 0, 0};\n"
    out += "emmisive[] = {%g, %g, %g, 1};\nspecular[] = {0.2, 0.2, 0.2, 1};\nspecularPower = 20;\n" % tuple(emissive)
    out += 'PixelShaderID = "Super";\nVertexShaderID = "Super";\n'
    out += stage(1, "#(argb,8,8,3)color(0.5,0.5,1,1,NOHQ)")
    out += stage(2, "#(argb,8,8,3)color(0.5,0.5,0.5,1,DT)")
    out += stage(3, "#(argb,8,8,3)color(0,0,0,0,MC)")
    out += stage(4, "#(argb,8,8,3)color(1,1,1,1,AS)")
    out += stage(5, "#(argb,8,8,3)color(1,0.2,0.3,1,SMDI)")
    out += stage(6, "#(ai,64,64,1)fresnel(1.5,0.8)", "none")
    out += stage(7, S.ENV_MAP, "none", '\tuseWorldEnvMap = "true";\n')
    return out


# Alpha-tested (not blended) materials - renderFlags as in Bohemia's Test_Clutter grass rvmat.
ALPHA_TEST = {"sky_foliage", "sky_roadmark", "sky_decal_cracks", "sky_decal_graffiti", "sky_vegetation"}

RVMATS = {
    "sky_concrete": ("sky_concrete", 20), "sky_metal": ("sky_metal", 60), "sky_glass": ("sky_glass", 120), "sky_glassfar": ("sky_glassfar", 80),
    "sky_tile": ("sky_tile", 50), "sky_carpet": ("sky_carpet", 5), "sky_wallpaper": ("sky_wallpaper", 10),
    "sky_roofmark": ("sky_roofmark", 15), "sky_asphalt": ("sky_asphalt", 10),
    # kit (batch 1+)
    "sky_paver": ("sky_paver", 10), "sky_roadmark": ("sky_roadmark", 15), "sky_rust": ("sky_rust", 25),
    "sky_foliage": ("sky_foliage", 5), "sky_atlas": ("sky_atlas", 30), "sky_billboard": ("sky_billboard", 15),
    # batch 2
    "sky_decal_dirt": ("sky_decal_dirt", 5), "sky_decal_cracks": ("sky_decal_cracks", 5),
    "sky_decal_graffiti": ("sky_decal_graffiti", 10), "sky_windows": ("sky_windows", 60),
    "sky_brick": ("sky_brick", 10), "sky_concpanel": ("sky_concpanel", 15),
    # batch 3
    "sky_wood": ("sky_wood", 30), "sky_fabric": ("sky_fabric", 5),
    # realism pass (D53)
    "sky_ceiling": ("sky_ceiling", 5),
    # splendour pass (D55)
    "sky_marble": ("sky_marble", 90), "sky_parquet": ("sky_parquet", 40), "sky_paint": ("sky_paint", 10),
    "sky_stone": ("sky_stone", 60), "sky_textile": ("sky_textile", 5),
    # city buildings (D56)
    "sky_render": ("sky_render", 8), "sky_rubble": ("sky_rubble", 5), "sky_signs": ("sky_signs", 40),
    # DayZ ambiance (D59)
    "sky_decal_grime": ("sky_decal_grime", 5), "sky_vegetation": ("sky_vegetation", 5),
    "sky_wall_brick": ("sky_wall_brick", 10), "sky_wall_panel": ("sky_wall_panel", 15),
    "sky_wall_limestone": ("sky_wall_limestone", 20),
    "sky_wall_render_cream": ("sky_wall_render_cream", 8), "sky_wall_render_ochre": ("sky_wall_render_ochre", 8),
    "sky_wall_render_grey": ("sky_wall_render_grey", 8), "sky_wall_render_white": ("sky_wall_render_white", 8),
}


# ------------------------------------------------------------------ kit (skyspec.KIT)
KIT_PATCH = {"sky_street": "SKY_Skyline_Street", "sky_props": "SKY_Skyline_Props", "sky_floors": "SKY_Skyline_Floors",
             "sky_city": "SKY_Skyline_City"}


def kit_entries(pbo):
    return [(n, e) for n, e in S.KIT.items() if e["pbo"] == pbo]


def kit_config(pbo):
    prefix = S.MOD + "\\" + pbo
    out = HEADER + patches(KIT_PATCH[pbo], ["DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"])
    out += "\nclass CfgVehicles\n{\n\tclass HouseNoDestruct;\n"
    base = "Land_SKY_%s_Base" % pbo.split("_")[1].capitalize()
    out += "\tclass %s: HouseNoDestruct\n\t{\n\t\tscope = 0;\n\t};\n" % base
    for name, e in kit_entries(pbo):
        body = '\t\tscope = 1;\n\t\tmodel = "%s\\%s";\n' % (prefix, e["p3d"])
        if e["desc"]:
            body = "\t\t// %s\n" % e["desc"] + body
        if e["variants"]:
            body += '\t\thiddenSelections[] = {"camo"};\n'
            first = sorted(e["variants"])[0]
            body += '\t\thiddenSelectionsTextures[] = {"%s"};\n' % e["variants"][first]
        body += e.get("config_extra", "")
        if e.get("doors"):
            body += kit_doors_config(e["doors"])
        out += "\tclass %s: %s\n\t{\n%s\t};\n" % (e["cls"], base, body)
        for vcls, texpath in sorted(e["variants"].items()):
            out += '\tclass %s: %s\n\t{\n\t\thiddenSelectionsTextures[] = {"%s"};\n\t};\n' % (vcls, e["cls"], texpath)
    return out + "};\n"


def kit_doors_config(doors):
    """Doors on a prop: same Test_Building pattern and sounds as the Tower A lobby door."""
    out = "\t\tclass Doors\n\t\t{\n"
    for d in doors:
        out += """\t\t\tclass %s
\t\t\t{
\t\t\t\tdisplayName = "%s";
\t\t\t\tcomponent = "%s";
\t\t\t\tsoundPos = "%s_action";
\t\t\t\tanimPeriod = 0.8;
\t\t\t\tinitPhase = 0.0;
\t\t\t\tinitOpened = 0.0;
\t\t\t\tsoundOpen = "doorMetalSmallOpen";
\t\t\t\tsoundClose = "doorMetalSmallClose";
\t\t\t\tsoundLocked = "doorMetalSmallRattle";
\t\t\t\tsoundOpenABit = "doorMetalSmallOpenABit";
\t\t\t};
""" % (d["name"], d["display"], d["name"], d["name"])
    return out + "\t\t};\n" + damage_system_static([d["name"] for d in doors])


def kit_door_anims(name, doors):
    """model.cfg skeleton + rotation per door; swing = DOOR_SWING_SIGN * orient (P1)."""
    skel = "\tclass SKY_Skeleton_%s: Default\n\t{\n\t\tskeletonInherit = \"Default\";\n" % name
    skel += "\t\tskeletonBones[] = {%s};\n\t};\n" % ", ".join('"%s",""' % d["name"] for d in doors)
    anims = ""
    for d in doors:
        anims += """\t\t\tclass %s_rot
\t\t\t{
\t\t\t\ttype = "rotation";
\t\t\t\tselection = "%s";
\t\t\t\tsource = "%s";
\t\t\t\taxis = "%s_axis";
\t\t\t\tmemory = 1;
\t\t\t\tminValue = 0;
\t\t\t\tmaxValue = 1;
\t\t\t\tangle0 = 0;
\t\t\t\tangle1 = %g;
\t\t\t};
""" % (d["name"], d["name"], d["name"], d["name"], S.DOOR_SWING_SIGN * d["orient"] * S.DOOR_OPEN_ANGLE * d["scale"])
    return {"skeleton": skel, "skeleton_name": "SKY_Skeleton_%s" % name, "animations": anims}


def kit_model_cfg(pbo):
    out = HEADER + """class CfgSkeletons
{
\tclass Default
\t{
\t\tisDiscrete = 1;
\t\tskeletonInherit = "";
\t\tskeletonBones[] = {};
\t};
%s};
class CfgModels
{
\tclass Default
\t{
\t\tsectionsInherit = "";
\t\tsections[] = {};
\t\tskeletonName = "";
\t};
"""
    skel = ""
    for name, e in kit_entries(pbo):
        stem = e["p3d"][:-4]
        body = ""
        if e["variants"]:
            body += '\t\tsections[] = {"camo"};\n'
        anim = e.get("model_anims") or (kit_door_anims(name, e["doors"]) if e.get("doors") else None)
        if anim:
            skel += anim["skeleton"]
            body += '\t\tskeletonName = "%s";\n\t\tclass Animations\n\t\t{\n%s\t\t};\n' % (anim["skeleton_name"], anim["animations"])
        out += "\tclass %s: Default\n\t{\n%s\t};\n" % (stem, body) if body else "\tclass %s: Default {};\n" % stem
    return (out % skel) + "};\n"


# ------------------------------------------------------------------ tower config
def damage_system_static(door_names):
    zones = ""
    for d in door_names:
        zones += """\t\t\t\tclass %s
\t\t\t\t{
\t\t\t\t\tclass Health { hitpoints = 1000; transferToGlobalCoef = 0; };
\t\t\t\t\tcomponentNames[] = {"%s"};
\t\t\t\t\tfatalInjuryCoef = -1;
\t\t\t\t\tclass ArmorType
\t\t\t\t\t{
\t\t\t\t\t\tclass Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t\tclass Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t\tclass %s { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t};
\t\t\t\t};
""" % (d, d, S.ARMOR_EXPLOSION_CLASS)
    return """\t\tclass DamageSystem
\t\t{
\t\t\tclass GlobalHealth { class Health { hitpoints = 1000; }; };
\t\t\tclass GlobalArmor
\t\t\t{
\t\t\t\tclass Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\tclass Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\tclass %s { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t};
\t\t\tclass DamageZones
\t\t\t{
%s\t\t\t};
\t\t};
""" % (S.ARMOR_EXPLOSION_CLASS, zones)


def tower_config():
    model = lambda c: S.PREFIX_TOWER + "\\" + S.P3D[c]
    stops = S.elevator_stops()
    C = S.CORE
    d = S.KEYCARD_DOOR
    out = HEADER + patches("SKY_Skyline_TowerA", ["DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"])
    out += "\nclass CfgVehicles\n{\n\tclass HouseNoDestruct;\n"
    out += "\tclass Land_SKY_TowerA_Base: HouseNoDestruct\n\t{\n\t\tscope = 0;\n\t};\n"
    for c in (S.CLASS_FLOOR, S.CLASS_ROOF):
        out += "\tclass %s: Land_SKY_TowerA_Base\n\t{\n\t\tscope = 1;\n\t\tmodel = \"%s\";\n\t};\n" % (c, model(c))
    # Lobby: keycard door (doors-on-buildings pattern from Test_Building).
    out += """\tclass %s: Land_SKY_TowerA_Base
\t{
\t\tscope = 1;
\t\tmodel = "%s";
\t\tclass Doors
\t\t{
\t\t\tclass %s
\t\t\t{
\t\t\t\tdisplayName = "Security door";
\t\t\t\tcomponent = "%s";
\t\t\t\tsoundPos = "%s_action";
\t\t\t\tanimPeriod = 1.0;
\t\t\t\tinitPhase = 0.0;
\t\t\t\tinitOpened = 0.0;
\t\t\t\tsoundOpen = "doorMetalSmallOpen";
\t\t\t\tsoundClose = "doorMetalSmallClose";
\t\t\t\tsoundLocked = "doorMetalSmallRattle";
\t\t\t\tsoundOpenABit = "doorMetalSmallOpenABit";
\t\t\t};
\t\t};
\t\t// SKY keycard doors: Doors class names + required tier (read by script class Land_SKY_TowerA_Lobby).
\t\tskyKeycardDoors[] = {"%s"};
\t\tskyKeycardTiers[] = {%d};
\t\tskyKeycardRelockMs = %d;
\t\t// Security room interior, model space {x0, x1, z0, z1} (exit button works only inside).
\t\tskySecurityRoom[] = {%g, %g, %g, %g};
%s\t};
""" % (S.CLASS_LOBBY, model(S.CLASS_LOBBY), d["name"], d["name"], d["name"], d["name"], d["required_tier"],
       d["relock_ms"], S.SECURITY_ROOM["x"][0] + S.WALL_T / 2, S.SECURITY_ROOM["x"][1],
       S.SECURITY_ROOM["y"][0] + S.WALL_T / 2, S.SECURITY_ROOM["y"][1], damage_system_static([d["name"]]))
    # Cores: elevator (user animation sources, script-driven); tall cores D58 = same parameters, more stops.
    for _k, (ccls, spec) in S.CORE_VARIANTS.items():
        stops = S.elevator_stops(spec)
        src = ""
        for i in range(len(stops)):
            src += "\t\t\tclass elev_door_l%d\n\t\t\t{\n\t\t\t\tsource = \"user\";\n\t\t\t\tanimPeriod = 1.2;\n\t\t\t\tinitPhase = 0;\n\t\t\t};\n" % i
        out += """\tclass %s: Land_SKY_TowerA_Base
\t{
\t\tscope = 1;
\t\tmodel = "%s";
\t\tclass AnimationSources
\t\t{
%s\t\t};
\t\t// SKY elevator parameters (read by script class Land_SKY_TowerA_Core).
\t\tskyStops[] = {%s};
\t\tskyMaxOccupants = %d;
\t\tskyCooldownMs = %d;
\t\tskyDoorOpenMs = %d;
\t\tskyTravelMsBase = %d;
\t\tskyTravelMsPerStop = %d;
\t\tskyCabHalfX = %g;
\t\tskyCabHalfY = %g;
\t\tskyCabHeight = %g;
\t\tskyPanelReach = 1.6;
\t};
""" % (ccls, model(ccls), src, ", ".join("%g" % s for s in stops), C["max_occupants"],
           C["cooldown_ms"], C["door_open_ms"], C["travel_ms_base"], C["travel_ms_per_stop"],
           (C["cab_x"][1] - C["cab_x"][0]) / 2, (C["elev_y"][1] - S.WALL_T - C["elev_y"][0]) / 2, C["cab_h"])
    return out + "};\n"


def _core_anims(n):
    anims = ""
    for i in range(n):
        for leaf in ("a", "b"):
            anims += """\t\t\tclass Elev_L%d_%s
\t\t\t{
\t\t\t\ttype = "translation";
\t\t\t\tsource = "elev_door_l%d";
\t\t\t\tselection = "elev_door_l%d_%s";
\t\t\t\taxis = "elev_door_l%d_%s_axis";
\t\t\t\tmemory = 1;
\t\t\t\tminValue = 0;
\t\t\t\tmaxValue = 1;
\t\t\t\toffset0 = 0;
\t\t\t\toffset1 = 1;
\t\t\t};
""" % (i, leaf.upper(), i, i, leaf, i, leaf)
    return anims


def tower_model_cfg():
    d = S.KEYCARD_DOOR
    stem = lambda c: S.P3D[c][:-4]
    skels, models = "", ""
    for k, (ccls, spec) in S.CORE_VARIANTS.items():
        n = len(S.elevator_stops(spec))
        sk = "SKY_Skeleton_Core" + ("" if k == "A" else k[1:])
        bones = []
        for i in range(n):
            bones += ['"elev_door_l%d_a",""' % i, '"elev_door_l%d_b",""' % i]
        skels += """\tclass %s: Default
\t{
\t\tskeletonInherit = "Default";
\t\tskeletonBones[] =
\t\t{
\t\t\t%s
\t\t};
\t};
""" % (sk, ",\n\t\t\t".join(bones))
        models += """\tclass %s: Default
\t{
\t\tskeletonName = "%s";
\t\tclass Animations
\t\t{
%s\t\t};
\t};
""" % (stem(ccls), sk, _core_anims(n))
    out = HEADER + """class CfgSkeletons
{
\tclass Default
\t{
\t\tisDiscrete = 1;
\t\tskeletonInherit = "";
\t\tskeletonBones[] = {};
\t};
\tclass SKY_Skeleton_Lobby: Default
\t{
\t\tskeletonInherit = "Default";
\t\tskeletonBones[] = {"%s",""};
\t};
%s};
""" % (d["name"], skels)
    out += """class CfgModels
{
\tclass Default
\t{
\t\tsectionsInherit = "";
\t\tsections[] = {};
\t\tskeletonName = "";
\t};
\tclass %s: Default {};
\tclass %s: Default {};
\tclass %s: Default
\t{
\t\tskeletonName = "SKY_Skeleton_Lobby";
\t\tclass Animations
\t\t{
\t\t\tclass Door_Sec
\t\t\t{
\t\t\t\ttype = "rotation";
\t\t\t\tselection = "%s";
\t\t\t\tsource = "%s";
\t\t\t\taxis = "%s_axis";
\t\t\t\tmemory = 1;
\t\t\t\tminValue = 0;
\t\t\t\tmaxValue = 1;
\t\t\t\tangle0 = 0;
\t\t\t\tangle1 = %g;
\t\t\t};
\t\t};
\t};
%s};
""" % (stem(S.CLASS_FLOOR), stem(S.CLASS_ROOF), stem(S.CLASS_LOBBY), d["name"], d["name"], d["name"],
       S.DOOR_SWING_SIGN * S.DOOR_OPEN_ANGLE, models)
    return out


def tower_cores_script():
    """Script classes for the tall cores: same elevator logic, stops from their config (D58)."""
    out = ("// GENERATED by assets/gen_configs.py from skyspec.CORE_VARIANTS (tall tower cores, D58) - do not edit.\n"
           "// The elevator reads skyStops[] from config; a taller core only needs its own class name.\n")
    for k, (ccls, _spec) in sorted(S.CORE_VARIANTS.items()):
        if k != "A":
            out += "\nclass %s extends Land_SKY_TowerA_Core\n{\n}\n" % ccls
    return out


# ------------------------------------------------------------------ items
def items_config():
    dpath = S.PREFIX_ITEMS + "\\data\\"
    out = HEADER + patches("SKY_Skyline_Items", ["DZ_Data", "SKY_Skyline_Scripts"])
    out += """
class CfgVehicles
{
\tclass Inventory_Base;
\tclass SKY_Keycard_Base: Inventory_Base
\t{
\t\tscope = 0;
\t\tdisplayName = "Access keycard";
\t\tdescriptionShort = "Magnetic access card for Skyline building security doors.";
\t\tmodel = "%s\\sky_keycard.p3d";
\t\tweight = 10;
\t\titemSize[] = {1, 1};
\t\trotationFlags = 17;
\t\thiddenSelections[] = {"camo"};
\t\tskyTier = 0;
\t\tclass DamageSystem
\t\t{
\t\t\tclass GlobalHealth
\t\t\t{
\t\t\t\tclass Health
\t\t\t\t{
\t\t\t\t\thitpoints = 100;
\t\t\t\t\thealthLevels[] =
\t\t\t\t\t{
\t\t\t\t\t\t{1.0, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.7, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.5, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.3, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.0, {"%ssky_keycard.rvmat"}}
\t\t\t\t\t};
\t\t\t\t};
\t\t\t};
\t\t};
\t};
""" % ((S.PREFIX_ITEMS,) + (dpath,) * 5)
    for tier, name in S.KEYCARD_TIERS.items():
        out += """\tclass %s: SKY_Keycard_Base
\t{
\t\tscope = 2;
\t\tdisplayName = "Access keycard (level %d)";
\t\thiddenSelectionsTextures[] = {"%ssky_keycard_t%d_co.paa"};
\t\tskyTier = %d;
\t};
""" % (name, tier, dpath, tier, tier)
    out += "};\n"
    return out


def keycard_rvmat():
    d = S.PREFIX_ITEMS + "\\data\\sky_keycard"
    out = HEADER
    out += "ambient[] = {1, 1, 1, 1};\ndiffuse[] = {1, 1, 1, 1};\nforcedDiffuse[] = {0, 0, 0, 0};\n"
    out += "emmisive[] = {0, 0, 0, 1};\nspecular[] = {0.5, 0.5, 0.5, 1};\nspecularPower = 50;\n"
    out += 'PixelShaderID = "Super";\nVertexShaderID = "Super";\n'
    out += stage(1, d + "_nohq.paa")
    out += stage(2, "#(argb,8,8,3)color(0.5,0.5,0.5,1,DT)")
    out += stage(3, "#(argb,8,8,3)color(0,0,0,0,MC)")
    out += stage(4, "#(argb,8,8,3)color(1,1,1,1,AS)")
    out += stage(5, d + "_smdi.paa")
    out += stage(6, "#(ai,64,64,1)fresnel(1.5,0.8)", "none")
    out += stage(7, S.ENV_MAP, "none", '\tuseWorldEnvMap = "true";\n')
    return out


def city_lit_script():
    """Script classes for the intact city buildings: night lights at light_1 / light_4
    (SKY_LitBuilding, D55). Damaged and ruined buildings stay dark (plain House)."""
    out = ("// GENERATED by assets/gen_configs.py from skyspec.KIT (city buildings, D56) - do not edit.\n"
           "// Intact buildings light up at night; offices / civic / industrial use the cool office light.\n")
    for name, e in sorted(S.KIT.items()):
        c = e.get("city")
        if not c or c["ruin"] != 0 or not c.get("archetype") or S.CITY_ARCHETYPES[c["archetype"]].get("special"):
            continue                                       # lots, kit pieces, substations: no lights
        group = S.CITY_ARCHETYPES[c["archetype"]]["group"]
        body = ""
        if group in ("commercial", "civic", "industrial"):
            body = "\n\toverride protected typename SkyLightType()\n\t{\n\t\treturn SKY_OfficeLight;\n\t}\n"
        out += "\nclass %s extends SKY_LitBuilding\n{%s}\n" % (e["cls"], body)
    return out


def outputs():
    files = {
        "sky_textures/config.cpp": HEADER + patches("SKY_Skyline_Textures", ["DZ_Data"]),
        "sky_towera/config.cpp": tower_config(),
        "sky_towera/model.cfg": tower_model_cfg(),
        "sky_items/config.cpp": items_config(),
        "sky_items/data/sky_keycard.rvmat": keycard_rvmat(),
        "sky_items/model.cfg": HEADER + """class CfgSkeletons
{
\tclass Default
\t{
\t\tisDiscrete = 1;
\t\tskeletonInherit = "";
\t\tskeletonBones[] = {};
\t};
};
class CfgModels
{
\tclass Default
\t{
\t\tsectionsInherit = "";
\t\tsections[] = {};
\t\tskeletonName = "";
\t};
\tclass sky_keycard: Default
\t{
\t\tsections[] = {"camo"};
\t};
};
""",
    }
    for name, (base, power) in RVMATS.items():
        text = rvmat_super(base, power)
        if name in ALPHA_TEST:
            text = text.replace('PixelShaderID', 'renderFlags[] = {"AlphaTest32"};\nPixelShaderID', 1)
        files["sky_textures/data/%s.rvmat" % name] = text
    files["sky_textures/data/sky_lamp.rvmat"] = rvmat_flat(S.EMISSIVE_LAMP)
    files["sky_textures/data/sky_lamp_cool.rvmat"] = rvmat_flat(S.EMISSIVE_LAMP_COOL)
    files["sky_textures/data/sky_windows_lit.rvmat"] = rvmat_super("sky_windows", 60, tuple(S.EMISSIVE_WINDOW))
    files["sky_scripts/scripts/4_World/SKY/SKY_CityLit.c"] = city_lit_script()
    files["sky_scripts/scripts/4_World/SKY/SKY_TowerCores.c"] = tower_cores_script()
    for pbo in KIT_PATCH:
        if kit_entries(pbo):
            files["%s/config.cpp" % pbo] = kit_config(pbo)
            files["%s/model.cfg" % pbo] = kit_model_cfg(pbo)
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    for rel, text in outputs().items():
        path = os.path.join(ADDONS, rel.replace("/", os.sep))
        text = text.replace("\r\n", "\n")
        cur = open(path, encoding="utf-8").read().replace("\r\n", "\n") if os.path.exists(path) else None
        if cur != text:
            stale.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
                    fh.write(text)
    if a.check and stale:
        print("stale generated files:", ", ".join(stale))
        sys.exit(1)
    print("up to date" if not stale else "wrote: " + ", ".join(stale))


if __name__ == "__main__":
    main()
