#!/usr/bin/env python3
"""Generate config.cpp / model.cfg / rvmat files for SKY_Skyline from skyspec.

    python mods/SKY_Skyline/assets/gen_configs.py            # writes into addons/
    python mods/SKY_Skyline/assets/gen_configs.py --check    # exit 1 if files are stale

Outputs are committed (reviewable diffs); re-run after editing skyspec.py.
Syntax follows Bohemia's DayZ-Samples (Test_Building config.cpp/model.cfg,
Test_ClothingRetexture hiddenSelections) - see SLICE_REPORT.md for sources.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import skyspec as S  # noqa: E402

ADDONS = os.path.join(os.path.dirname(HERE), "addons")
HEADER = "// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.\n"


def patches(name, required):
    req = ", ".join('"%s"' % r for r in required)
    return ("class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[] = {};\n\t\tweapons[] = {};\n"
            "\t\trequiredVersion = 0.1;\n\t\trequiredAddons[] = {%s};\n\t};\n};\n" % (name, req))


# ------------------------------------------------------------------ rvmat
UVT = ("\tclass uvTransform\n\t{\n\t\taside[] = {1, 0, 0};\n\t\tup[] = {0, 1, 0};\n"
       "\t\tdir[] = {0, 0, 1};\n\t\tpos[] = {0, 0, 0};\n\t};\n")


def stage(n, texture, uv_source="tex", extra=""):
    body = '\ttexture = "%s";\n\tuvSource = "%s";\n' % (texture, uv_source)
    if uv_source == "tex":
        body += UVT
    return "class Stage%d\n{\n%s%s};\n" % (n, body, extra)


def rvmat_super(base, spec_power=40, emissive=(0, 0, 0)):
    """Standard 'Super' shader layout (Stage1 nohq, 2 detail, 3 macro, 4 as,
    5 smdi, 6 fresnel, 7 env). Detail/macro are neutral procedurals."""
    d = S.PREFIX_TEX + "\\data\\" + base
    out = HEADER
    out += "ambient[] = {1, 1, 1, 1};\ndiffuse[] = {1, 1, 1, 1};\nforcedDiffuse[] = {0, 0, 0, 0};\n"
    out += "emmisive[] = {%g, %g, %g, 1};\nspecular[] = {0.7, 0.7, 0.7, 1};\nspecularPower = %d;\n" % (
        emissive + (spec_power,))
    out += 'PixelShaderID = "Super";\nVertexShaderID = "Super";\n'
    out += stage(1, d + "_nohq.paa")
    out += stage(2, "#(argb,8,8,3)color(0.5,0.5,0.5,1,DT)")
    out += stage(3, "#(argb,8,8,3)color(0,0,0,0,MC)")
    out += stage(4, d + "_as.paa")
    out += stage(5, d + "_smdi.paa")
    out += stage(6, "#(ai,64,64,1)fresnel(1.5,0.8)", "none")
    # Env map path follows the vanilla convention; confirmed by Check-SkyAssets.ps1 on P:.
    out += stage(7, "dz\\data\\data\\env_land_co.paa", "none", '\tuseWorldEnvMap = "true";\n')
    return out


RVMATS = {
    "sky_concrete": ("sky_concrete", 20), "sky_metal": ("sky_metal", 60), "sky_glass": ("sky_glass", 120), "sky_glassfar": ("sky_glassfar", 80),
    "sky_tile": ("sky_tile", 50), "sky_carpet": ("sky_carpet", 5), "sky_wallpaper": ("sky_wallpaper", 10),
    "sky_roofmark": ("sky_roofmark", 15), "sky_asphalt": ("sky_asphalt", 10),
}


# ------------------------------------------------------------------ tower config
def damage_system_static(door_names):
    zones = ""
    for d in door_names:
        zones += """\t\t\t\tclass %s
\t\t\t\t{
\t\t\t\t\tclass Health { hitpoints = 1000; transferToGlobalCoef = 0; };
\t\t\t\t\tcomponentNames[] = {"%s"};
\t\t\t\t\tfatalInjuryCoef = -1;
\t\t\t\t\tclass ArmorType
\t\t\t\t\t{
\t\t\t\t\t\tclass Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t\tclass Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t\tclass FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\t\t};
\t\t\t\t};
""" % (d, d)
    return """\t\tclass DamageSystem
\t\t{
\t\t\tclass GlobalHealth { class Health { hitpoints = 1000; }; };
\t\t\tclass GlobalArmor
\t\t\t{
\t\t\t\tclass Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\tclass Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t\tclass FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
\t\t\t};
\t\t\tclass DamageZones
\t\t\t{
%s\t\t\t};
\t\t};
""" % zones


def tower_config():
    model = lambda c: S.PREFIX_TOWER + "\\" + S.P3D[c]
    stops = S.elevator_stops()
    C = S.CORE
    d = S.KEYCARD_DOOR
    out = HEADER + patches("SKY_Skyline_TowerA", ["DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"])
    out += "\nclass CfgVehicles\n{\n\tclass HouseNoDestruct;\n"
    out += "\tclass Land_SKY_TowerA_Base: HouseNoDestruct\n\t{\n\t\tscope = 0;\n\t};\n"
    for c in (S.CLASS_FLOOR, S.CLASS_ROOF):
        out += "\tclass %s: Land_SKY_TowerA_Base\n\t{\n\t\tscope = 1;\n\t\tmodel = \"%s\";\n\t};\n" % (c, model(c))
    # Lobby: keycard door (doors-on-buildings pattern from Test_Building).
    out += """\tclass %s: Land_SKY_TowerA_Base
\t{
\t\tscope = 1;
\t\tmodel = "%s";
\t\tclass Doors
\t\t{
\t\t\tclass %s
\t\t\t{
\t\t\t\tdisplayName = "Security door";
\t\t\t\tcomponent = "%s";
\t\t\t\tsoundPos = "%s_action";
\t\t\t\tanimPeriod = 1.0;
\t\t\t\tinitPhase = 0.0;
\t\t\t\tinitOpened = 0.0;
\t\t\t\tsoundOpen = "doorMetalSmallOpen";
\t\t\t\tsoundClose = "doorMetalSmallClose";
\t\t\t\tsoundLocked = "doorMetalSmallRattle";
\t\t\t\tsoundOpenABit = "doorMetalSmallOpenABit";
\t\t\t};
\t\t};
\t\t// SKY keycard doors: Doors class names + required tier (read by script class Land_SKY_TowerA_Lobby).
\t\tskyKeycardDoors[] = {"%s"};
\t\tskyKeycardTiers[] = {%d};
\t\tskyKeycardRelockMs = %d;
\t\t// Security room interior, model space {x0, x1, z0, z1} (exit button works only inside).
\t\tskySecurityRoom[] = {%g, %g, %g, %g};
%s\t};
""" % (S.CLASS_LOBBY, model(S.CLASS_LOBBY), d["name"], d["name"], d["name"], d["name"], d["required_tier"],
       d["relock_ms"], S.SECURITY_ROOM["x"][0] + S.WALL_T / 2, S.SECURITY_ROOM["x"][1],
       S.SECURITY_ROOM["y"][0] + S.WALL_T / 2, S.SECURITY_ROOM["y"][1], damage_system_static([d["name"]]))
    # Core: elevator (user animation sources, script-driven).
    src = ""
    for i in range(len(stops)):
        src += "\t\t\tclass elev_door_l%d\n\t\t\t{\n\t\t\t\tsource = \"user\";\n\t\t\t\tanimPeriod = 1.2;\n\t\t\t\tinitPhase = 0;\n\t\t\t};\n" % i
    out += """\tclass %s: Land_SKY_TowerA_Base
\t{
\t\tscope = 1;
\t\tmodel = "%s";
\t\tclass AnimationSources
\t\t{
%s\t\t};
\t\t// SKY elevator parameters (read by script class Land_SKY_TowerA_Core).
\t\tskyStops[] = {%s};
\t\tskyMaxOccupants = %d;
\t\tskyCooldownMs = %d;
\t\tskyDoorOpenMs = %d;
\t\tskyTravelMsBase = %d;
\t\tskyTravelMsPerStop = %d;
\t\tskyCabHalfX = %g;
\t\tskyCabHalfY = %g;
\t\tskyCabHeight = %g;
\t\tskyPanelReach = 1.6;
\t};
};
""" % (S.CLASS_CORE, model(S.CLASS_CORE), src, ", ".join("%g" % s for s in stops), C["max_occupants"],
       C["cooldown_ms"], C["door_open_ms"], C["travel_ms_base"], C["travel_ms_per_stop"],
       (C["cab_x"][1] - C["cab_x"][0]) / 2, (C["elev_y"][1] - S.WALL_T - C["elev_y"][0]) / 2, C["cab_h"])
    return out


def tower_model_cfg():
    stops = S.elevator_stops()
    d = S.KEYCARD_DOOR
    bones_core = []
    for i in range(len(stops)):
        bones_core += ['"elev_door_l%d_a",""' % i, '"elev_door_l%d_b",""' % i]
    out = HEADER + """class CfgSkeletons
{
\tclass Default
\t{
\t\tisDiscrete = 1;
\t\tskeletonInherit = "";
\t\tskeletonBones[] = {};
\t};
\tclass SKY_Skeleton_Lobby: Default
\t{
\t\tskeletonInherit = "Default";
\t\tskeletonBones[] = {"%s",""};
\t};
\tclass SKY_Skeleton_Core: Default
\t{
\t\tskeletonInherit = "Default";
\t\tskeletonBones[] =
\t\t{
\t\t\t%s
\t\t};
\t};
};
""" % (d["name"], ",\n\t\t\t".join(bones_core))
    anims = ""
    for i in range(len(stops)):
        for leaf in ("a", "b"):
            anims += """\t\t\tclass Elev_L%d_%s
\t\t\t{
\t\t\t\ttype = "translation";
\t\t\t\tsource = "elev_door_l%d";
\t\t\t\tselection = "elev_door_l%d_%s";
\t\t\t\taxis = "elev_door_l%d_%s_axis";
\t\t\t\tmemory = 1;
\t\t\t\tminValue = 0;
\t\t\t\tmaxValue = 1;
\t\t\t\toffset0 = 0;
\t\t\t\toffset1 = 1;
\t\t\t};
""" % (i, leaf.upper(), i, i, leaf, i, leaf)
    stem = lambda c: S.P3D[c][:-4]
    out += """class CfgModels
{
\tclass Default
\t{
\t\tsectionsInherit = "";
\t\tsections[] = {};
\t\tskeletonName = "";
\t};
\tclass %s: Default {};
\tclass %s: Default {};
\tclass %s: Default
\t{
\t\tskeletonName = "SKY_Skeleton_Lobby";
\t\tclass Animations
\t\t{
\t\t\tclass Door_Sec
\t\t\t{
\t\t\t\ttype = "rotation";
\t\t\t\tselection = "%s";
\t\t\t\tsource = "%s";
\t\t\t\taxis = "%s_axis";
\t\t\t\tmemory = 1;
\t\t\t\tminValue = 0;
\t\t\t\tmaxValue = 1;
\t\t\t\tangle0 = 0;
\t\t\t\tangle1 = 1.4;
\t\t\t};
\t\t};
\t};
\tclass %s: Default
\t{
\t\tskeletonName = "SKY_Skeleton_Core";
\t\tclass Animations
\t\t{
%s\t\t};
\t};
};
""" % (stem(S.CLASS_FLOOR), stem(S.CLASS_ROOF), stem(S.CLASS_LOBBY), d["name"], d["name"], d["name"],
       stem(S.CLASS_CORE), anims)
    return out


# ------------------------------------------------------------------ items
def items_config():
    dpath = S.PREFIX_ITEMS + "\\data\\"
    out = HEADER + patches("SKY_Skyline_Items", ["DZ_Data", "SKY_Skyline_Scripts"])
    out += """
class CfgVehicles
{
\tclass Inventory_Base;
\tclass SKY_Keycard_Base: Inventory_Base
\t{
\t\tscope = 0;
\t\tdisplayName = "Access keycard";
\t\tdescriptionShort = "Magnetic access card for Skyline building security doors.";
\t\tmodel = "%s\\sky_keycard.p3d";
\t\tweight = 10;
\t\titemSize[] = {1, 1};
\t\trotationFlags = 17;
\t\thiddenSelections[] = {"camo"};
\t\tskyTier = 0;
\t\tclass DamageSystem
\t\t{
\t\t\tclass GlobalHealth
\t\t\t{
\t\t\t\tclass Health
\t\t\t\t{
\t\t\t\t\thitpoints = 100;
\t\t\t\t\thealthLevels[] =
\t\t\t\t\t{
\t\t\t\t\t\t{1.0, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.7, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.5, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.3, {"%ssky_keycard.rvmat"}},
\t\t\t\t\t\t{0.0, {"%ssky_keycard.rvmat"}}
\t\t\t\t\t};
\t\t\t\t};
\t\t\t};
\t\t};
\t};
""" % ((S.PREFIX_ITEMS,) + (dpath,) * 5)
    for tier, name in S.KEYCARD_TIERS.items():
        out += """\tclass %s: SKY_Keycard_Base
\t{
\t\tscope = 2;
\t\tdisplayName = "Access keycard (level %d)";
\t\thiddenSelectionsTextures[] = {"%ssky_keycard_t%d_co.paa"};
\t\tskyTier = %d;
\t};
""" % (name, tier, dpath, tier, tier)
    out += "};\n"
    return out


def keycard_rvmat():
    d = S.PREFIX_ITEMS + "\\data\\sky_keycard"
    out = HEADER
    out += "ambient[] = {1, 1, 1, 1};\ndiffuse[] = {1, 1, 1, 1};\nforcedDiffuse[] = {0, 0, 0, 0};\n"
    out += "emmisive[] = {0, 0, 0, 1};\nspecular[] = {0.5, 0.5, 0.5, 1};\nspecularPower = 50;\n"
    out += 'PixelShaderID = "Super";\nVertexShaderID = "Super";\n'
    out += stage(1, d + "_nohq.paa")
    out += stage(2, "#(argb,8,8,3)color(0.5,0.5,0.5,1,DT)")
    out += stage(3, "#(argb,8,8,3)color(0,0,0,0,MC)")
    out += stage(4, "#(argb,8,8,3)color(1,1,1,1,AS)")
    out += stage(5, d + "_smdi.paa")
    out += stage(6, "#(ai,64,64,1)fresnel(1.5,0.8)", "none")
    out += stage(7, "dz\\data\\data\\env_land_co.paa", "none", '\tuseWorldEnvMap = "true";\n')
    return out


def outputs():
    files = {
        "sky_textures/config.cpp": HEADER + patches("SKY_Skyline_Textures", ["DZ_Data"]),
        "sky_towera/config.cpp": tower_config(),
        "sky_towera/model.cfg": tower_model_cfg(),
        "sky_items/config.cpp": items_config(),
        "sky_items/data/sky_keycard.rvmat": keycard_rvmat(),
        "sky_items/model.cfg": HEADER + """class CfgSkeletons
{
\tclass Default
\t{
\t\tisDiscrete = 1;
\t\tskeletonInherit = "";
\t\tskeletonBones[] = {};
\t};
};
class CfgModels
{
\tclass Default
\t{
\t\tsectionsInherit = "";
\t\tsections[] = {};
\t\tskeletonName = "";
\t};
\tclass sky_keycard: Default
\t{
\t\tsections[] = {"camo"};
\t};
};
""",
    }
    for name, (base, power) in RVMATS.items():
        files["sky_textures/data/%s.rvmat" % name] = rvmat_super(base, power)
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    for rel, text in outputs().items():
        path = os.path.join(ADDONS, rel.replace("/", os.sep))
        text = text.replace("\r\n", "\n")
        cur = open(path, encoding="utf-8").read().replace("\r\n", "\n") if os.path.exists(path) else None
        if cur != text:
            stale.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
                    fh.write(text)
    if a.check and stale:
        print("stale generated files:", ", ".join(stale))
        sys.exit(1)
    print("up to date" if not stale else "wrote: " + ", ".join(stale))


if __name__ == "__main__":
    main()
