// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Landmarks
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Landmarks_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Fair_FerrisWheel: Land_SKY_Landmarks_Base
	{
		// 26 m Ferris wheel, 16 yellow gondolas, rust and saplings (Pripyat)
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_fair_ferriswheel.p3d";
	};
	class Land_SKY_Fair_Carousel: Land_SKY_Landmarks_Base
	{
		// chain-swing carousel: striped canopy, 16 swings, ring fence
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_fair_carousel.p3d";
	};
	class Land_SKY_Fair_BumperCars: Land_SKY_Landmarks_Base
	{
		// bumper-car pavilion: steel roof, fascia, 6 abandoned cars
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_fair_bumpercars.p3d";
	};
	class Land_SKY_Fair_Booth: Land_SKY_Landmarks_Base
	{
		// ticket / shooting-gallery booth with striped awning
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_fair_booth.p3d";
	};
	class Land_SKY_Fair_Gate: Land_SKY_Landmarks_Base
	{
		// LUNAPARK entrance arch with turnstiles
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_fair_gate.p3d";
	};
	class Land_SKY_Landfill: Land_SKY_Landmarks_Base
	{
		// municipal landfill: rubbish mounds, crushed cars, compactor shed, fence
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_landfill.p3d";
	};
	class Land_SKY_Stadium_Pitch: Land_SKY_Landmarks_Base
	{
		// football pitch: worn turf, lines, goals, dugouts, rail fence
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_stadium_pitch.p3d";
	};
	class Land_SKY_Stadium_Stand: Land_SKY_Landmarks_Base
	{
		// covered stand: 6 terraces with seats, roof on columns
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_stadium_stand.p3d";
	};
	class Land_SKY_Stadium_Floodlight: Land_SKY_Landmarks_Base
	{
		// 18 m lattice floodlight mast
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_stadium_floodlight.p3d";
	};
	class Land_SKY_ParkingLot_A: Land_SKY_Landmarks_Base
	{
		// surface car park: bays, lamp posts, barrier booth, wrecks
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_parkinglot_a.p3d";
	};
	class Land_SKY_ParkingLot_B: Land_SKY_Landmarks_Base
	{
		// small surface car park: one row of bays, wrecks
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_parkinglot_b.p3d";
	};
	class Land_SKY_ParkingLot_Metro: Land_SKY_Landmarks_Base
	{
		// car park hiding a sealed metro service hatch behind a van wreck
		scope = 1;
		model = "SKY_Skyline\sky_landmarks\sky_parkinglot_metro.p3d";
	};
};
