// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_CityRes
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_CityRes_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_City_Rowhouse_Intact: Land_SKY_CityRes_Base
	{
		// 3-storey brick townhouse, party walls both sides (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouse_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Rowhouse_Damaged: Land_SKY_CityRes_Base
	{
		// 3-storey brick townhouse, party walls both sides (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouse_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Rowhouse_Ruined: Land_SKY_CityRes_Base
	{
		// 3-storey brick townhouse, party walls both sides (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouse_ruined.p3d";
	};
	class Land_SKY_City_AptBlock_Intact: Land_SKY_CityRes_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblock_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlock_Damaged: Land_SKY_CityRes_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblock_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlock_Ruined: Land_SKY_CityRes_Base
	{
		// 5-storey precast apartment block, 2 flats per floor round a central stair (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblock_ruined.p3d";
	};
	class Land_SKY_City_RowhouseRender_Intact: Land_SKY_CityRes_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouserender_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhouseRender_Damaged: Land_SKY_CityRes_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouserender_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhouseRender_Ruined: Land_SKY_CityRes_Base
	{
		// 4-storey rendered townhouse with shutters, party walls (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhouserender_ruined.p3d";
	};
	class Land_SKY_City_RowhousePanel_Intact: Land_SKY_CityRes_Base
	{
		// 2-storey precast townhouse, party walls (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhousepanel_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhousePanel_Damaged: Land_SKY_CityRes_Base
	{
		// 2-storey precast townhouse, party walls (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhousepanel_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_RowhousePanel_Ruined: Land_SKY_CityRes_Base
	{
		// 2-storey precast townhouse, party walls (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_rowhousepanel_ruined.p3d";
	};
	class Land_SKY_City_AptBlockTall_Intact: Land_SKY_CityRes_Base
	{
		// 8-storey precast apartment block (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblocktall_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockTall_Damaged: Land_SKY_CityRes_Base
	{
		// 8-storey precast apartment block (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblocktall_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockTall_Ruined: Land_SKY_CityRes_Base
	{
		// 8-storey precast apartment block (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblocktall_ruined.p3d";
	};
	class Land_SKY_City_AptBlockBrick_Intact: Land_SKY_CityRes_Base
	{
		// 4-storey brick apartment block (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblockbrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockBrick_Damaged: Land_SKY_CityRes_Base
	{
		// 4-storey brick apartment block (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblockbrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_AptBlockBrick_Ruined: Land_SKY_CityRes_Base
	{
		// 4-storey brick apartment block (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_aptblockbrick_ruined.p3d";
	};
	class Land_SKY_City_Villa_Intact: Land_SKY_CityRes_Base
	{
		// detached 2-storey villa, pitched zinc roof (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villa_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Villa_Damaged: Land_SKY_CityRes_Base
	{
		// detached 2-storey villa, pitched zinc roof (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villa_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_Villa_Ruined: Land_SKY_CityRes_Base
	{
		// detached 2-storey villa, pitched zinc roof (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villa_ruined.p3d";
	};
	class Land_SKY_City_VillaBrick_Intact: Land_SKY_CityRes_Base
	{
		// detached 2-storey brick villa (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villabrick_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_VillaBrick_Damaged: Land_SKY_CityRes_Base
	{
		// detached 2-storey brick villa (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villabrick_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_VillaBrick_Ruined: Land_SKY_CityRes_Base
	{
		// detached 2-storey brick villa (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villabrick_ruined.p3d";
	};
	class Land_SKY_City_VillaStone_Intact: Land_SKY_CityRes_Base
	{
		// detached 2-storey stone villa (intact)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villastone_intact.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_VillaStone_Damaged: Land_SKY_CityRes_Base
	{
		// detached 2-storey stone villa (damaged)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villastone_damaged.p3d";
		class Doors
		{
			class door_front
			{
				displayName = "Door";
				component = "door_front";
				soundPos = "door_front_action";
				animPeriod = 0.8;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth { class Health { hitpoints = 1000; }; };
			class GlobalArmor
			{
				class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
				class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
			};
			class DamageZones
			{
				class door_front
				{
					class Health { hitpoints = 1000; transferToGlobalCoef = 0; };
					componentNames[] = {"door_front"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class Melee { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
						class FragGrenade { class Health { damage = 0; }; class Blood { damage = 0; }; class Shock { damage = 0; }; };
					};
				};
			};
		};
	};
	class Land_SKY_City_VillaStone_Ruined: Land_SKY_CityRes_Base
	{
		// detached 2-storey stone villa (ruined)
		scope = 1;
		model = "SKY_Skyline\sky_city_res\sky_city_villastone_ruined.p3d";
	};
};
