// GENERATED by assets/gen_configs.py from assets/skyspec.py - do not edit by hand.
class CfgPatches
{
	class SKY_Skyline_Street
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "SKY_Skyline_Textures", "SKY_Skyline_Scripts"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
	class Land_SKY_Street_Base: HouseNoDestruct
	{
		scope = 0;
	};
	class Land_SKY_Road_Straight: Land_SKY_Street_Base
	{
		// 8 x 12 m carriageway, centre dashed line
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_road_straight.p3d";
	};
	class Land_SKY_Road_Crossing: Land_SKY_Street_Base
	{
		// 8 x 12 m carriageway with crosswalk
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_road_crossing.p3d";
	};
	class Land_SKY_Intersection_4Way: Land_SKY_Street_Base
	{
		// 12 x 12 m junction with stop lines
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_intersection_4way.p3d";
	};
	class Land_SKY_Intersection_T: Land_SKY_Street_Base
	{
		// 12 x 12 m T junction (closed side = sidewalk)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_intersection_t.p3d";
	};
	class Land_SKY_Sidewalk: Land_SKY_Street_Base
	{
		// 2 x 12 m paver sidewalk with curb
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_sidewalk.p3d";
	};
	class Land_SKY_Sidewalk_Corner: Land_SKY_Street_Base
	{
		// 2 x 2 m sidewalk corner piece
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_sidewalk_corner.p3d";
	};
	class Land_SKY_Curb: Land_SKY_Street_Base
	{
		// 3 m curb stone (free placement)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_curb.p3d";
	};
	class Land_SKY_Manhole: Land_SKY_Street_Base
	{
		// 0.8 m cast-iron cover (Roadway only, no collision)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_manhole.p3d";
	};
	class Land_SKY_Street_Straight: Land_SKY_Street_Base
	{
		// 12 x 12 m street: road + both sidewalks
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_street_straight.p3d";
	};
	class Land_SKY_Street_Crossing: Land_SKY_Street_Base
	{
		// 12 x 12 m street with crosswalk
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_street_crossing.p3d";
	};
	class Land_SKY_Street_Intersection: Land_SKY_Street_Base
	{
		// 12 x 12 m 4-way junction with corner sidewalks built in
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_street_intersection.p3d";
	};
	class Land_SKY_StreetLight: Land_SKY_Street_Base
	{
		// 8 m pole street light (emissive head)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_streetlight.p3d";
	};
	class Land_SKY_TrafficLight: Land_SKY_Street_Base
	{
		// traffic light with 5 m arm (static atlas face, no emissive)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_trafficlight.p3d";
	};
	class Land_SKY_Barrier_Concrete: Land_SKY_Street_Base
	{
		// 3 m jersey barrier
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_barrier_concrete.p3d";
	};
	class Land_SKY_Barrier_Steel: Land_SKY_Street_Base
	{
		// 2.4 m crowd barrier
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_barrier_steel.p3d";
	};
	class Land_SKY_BusStop: Land_SKY_Street_Base
	{
		// 4 m shelter with bench and timetable
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_busstop.p3d";
	};
	class Land_SKY_Dumpster: Land_SKY_Street_Base
	{
		// 1.8 m waste container
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_dumpster.p3d";
		skySearch = "trash";
	};
	class Land_SKY_Planter: Land_SKY_Street_Base
	{
		// 1.5 m concrete planter with shrub
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_planter.p3d";
	};
	class Land_SKY_Wreck_Sedan: Land_SKY_Street_Base
	{
		// generic rusted sedan hulk (original shape)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_wreck_sedan.p3d";
	};
	class Land_SKY_Wreck_Van: Land_SKY_Street_Base
	{
		// generic burnt box van hulk (original shape)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_wreck_van.p3d";
	};
	class Land_SKY_Billboard: Land_SKY_Street_Base
	{
		// 6 x 3 m billboard, poster via hiddenSelections
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_billboard.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_billboard_a_co.paa"};
	};
	class Land_SKY_Billboard_A: Land_SKY_Billboard
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_billboard_a_co.paa"};
	};
	class Land_SKY_Billboard_B: Land_SKY_Billboard
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_billboard_b_co.paa"};
	};
	class Land_SKY_Billboard_C: Land_SKY_Billboard
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_billboard_c_co.paa"};
	};
	class Land_SKY_Billboard_D: Land_SKY_Billboard
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_billboard_d_co.paa"};
	};
	class Land_SKY_Decal_Dirt: Land_SKY_Street_Base
	{
		// 2 x 3 m run-off grime (alpha-blended)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_decal_dirt.p3d";
	};
	class Land_SKY_Decal_Cracks: Land_SKY_Street_Base
	{
		// 2 x 2 m plaster/concrete cracks (alpha-tested)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_decal_cracks.p3d";
	};
	class Land_SKY_Decal_Graffiti: Land_SKY_Street_Base
	{
		// 2 x 2 m original graffiti, 4 designs via hiddenSelections
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_decal_graffiti.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_decal_graffiti_a_ca.paa"};
	};
	class Land_SKY_Decal_Graffiti_A: Land_SKY_Decal_Graffiti
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_decal_graffiti_a_ca.paa"};
	};
	class Land_SKY_Decal_Graffiti_B: Land_SKY_Decal_Graffiti
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_decal_graffiti_b_ca.paa"};
	};
	class Land_SKY_Decal_Graffiti_C: Land_SKY_Decal_Graffiti
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_decal_graffiti_c_ca.paa"};
	};
	class Land_SKY_Decal_Graffiti_D: Land_SKY_Decal_Graffiti
	{
		hiddenSelectionsTextures[] = {"SKY_Skyline\sky_textures\data\sky_decal_graffiti_d_ca.paa"};
	};
	class Land_SKY_TrashBin: Land_SKY_Street_Base
	{
		// street litter bin with lid (searchable)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_trashbin.p3d";
		skySearch = "trash";
	};
	class Land_SKY_Hydrant_Wet: Land_SKY_Street_Base
	{
		// fire hydrant that still gives water (vanilla well behaviour)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_hydrant_wet.p3d";
	};
	class Land_SKY_Hydrant_Dry: Land_SKY_Street_Base
	{
		// dry fire hydrant (decoration)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_hydrant_dry.p3d";
	};
	class Land_SKY_SirenTower: Land_SKY_Street_Base
	{
		// civil-defence siren on a 10 m pole (city alarm event)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_sirentower.p3d";
	};
	class Land_SKY_Wreck_GarbageTruck: Land_SKY_Street_Base
	{
		// abandoned rear-loader garbage truck: ZiL-like cab, compactor body, spilled bags (hopper searchable)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_wreck_garbagetruck.p3d";
		skySearch = "trash";
	};
	class Land_SKY_Wreck_CityBus: Land_SKY_Street_Base
	{
		// abandoned LiAZ-style city bus: faded yellow, broken windows, flat tyres, seats inside
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_wreck_citybus.p3d";
	};
	class Land_SKY_RatNest: Land_SKY_Street_Base
	{
		// rat nest: rubbish heap with 9 rats; bites and gnaws nearby bases (SKY_Rats.c)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_ratnest.p3d";
	};
	class Land_SKY_HorseCarcass: Land_SKY_Street_Base
	{
		// dead horse on its side, half hide half bone (horses are blocked, D62)
		scope = 1;
		model = "SKY_Skyline\sky_street\sky_horsecarcass.p3d";
	};
};
