// SKY_Skyline sounds (D61-D62). sky_siren.ogg / sky_bark.ogg are generated by assets/sounds/gen_*.py (procedural, no samples).
// Played once per city alarm by SKY_CityAlarm.ClientPlaySiren (4_World/SKY/SKY_CityLife.c) at the siren tower.
// Format: vanilla CfgSoundShaders / CfgSoundSets (samples without extension, range + rangeCurve). PENDING P20:
// audible range and loudness in game.
class CfgPatches
{
	class SKY_Skyline_Sounds
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgSoundShaders
{
	class SKY_Siren_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_siren", 1}};
		volume = 1.0;
		range = 2500;
		rangeCurve[] = {{0, 1.0}, {300, 0.8}, {1000, 0.45}, {2000, 0.15}, {2500, 0.0}};
	};
	class SKY_Bark_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_bark", 1}};
		volume = 1.0;
		range = 150;
		rangeCurve[] = {{0, 1.0}, {40, 0.6}, {150, 0.0}};
	};
};

class CfgSoundSets
{
	class SKY_Siren_SoundSet
	{
		soundShaders[] = {"SKY_Siren_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 0;
	};
	class SKY_Bark_SoundSet
	{
		soundShaders[] = {"SKY_Bark_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 0;
	};
};
