// SKY_Skyline sounds (D61-D65). Every .ogg is generated by assets/sounds/gen_*.py (procedural, no samples).
// Format: vanilla CfgSoundShaders / CfgSoundSets (samples without extension, range + rangeCurve). PENDING P20/P32:
// audible range and loudness in game.
class CfgPatches
{
	class SKY_Skyline_Sounds
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgSoundShaders
{
	// city alarm, once per alarm (SKY_CityLife.c)
	class SKY_Siren_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_siren", 1}};
		volume = 1;
		range = 2500;
		rangeCurve[] = {{0, 1.0}, {300, 0.8}, {1000, 0.45}, {2000, 0.15}, {2500, 0.0}};
	};
	// guard kennel bark (SKY_CreatureLife.c)
	class SKY_Bark_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_bark", 1}};
		volume = 1;
		range = 150;
		rangeCurve[] = {{0, 1.0}, {40, 0.6}, {150, 0.0}};
	};
	// hypermarket tube hum loop (SKY_Ambience.c)
	class SKY_Hum_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_hum", 1}};
		volume = 0.5;
		range = 30;
		rangeCurve[] = {{0, 0.5}, {10, 0.3}, {30, 0.0}};
	};
	// sewer drips loop (SKY_Ambience.c)
	class SKY_Drips_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_drips", 1}};
		volume = 0.7;
		range = 25;
		rangeCurve[] = {{0, 0.7}, {10, 0.35}, {25, 0.0}};
	};
	// Ferris wheel creak + wind loop (SKY_Ambience.c)
	class SKY_Creak_SoundShader
	{
		samples[] = {{"SKY_Skyline\sky_sounds\data\sky_creak", 1}};
		volume = 0.8;
		range = 60;
		rangeCurve[] = {{0, 0.8}, {20, 0.45}, {60, 0.0}};
	};
};

class CfgSoundSets
{
	class SKY_Siren_SoundSet
	{
		soundShaders[] = {"SKY_Siren_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 0;
	};
	class SKY_Bark_SoundSet
	{
		soundShaders[] = {"SKY_Bark_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 0;
	};
	class SKY_Hum_SoundSet
	{
		soundShaders[] = {"SKY_Hum_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 1;
	};
	class SKY_Drips_SoundSet
	{
		soundShaders[] = {"SKY_Drips_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 1;
	};
	class SKY_Creak_SoundSet
	{
		soundShaders[] = {"SKY_Creak_SoundShader"};
		volumeFactor = 1.0;
		frequencyFactor = 1.0;
		spatial = 1;
		doppler = 0;
		loop = 1;
	};
};
